import { example, exercise, makeModule, pianoTask, prose, reflection } from './builder';

export const module09 = makeModule(
  'm09',
  9,
  'Hear the bass and refine harmony',
  'Separate root from bass, slow the harmonic rhythm, and add two chords that sharpen a cadence.',
  [
    {
      id: 'm09-l01',
      title: 'Root versus bass',
      objective: 'Identify a chord’s root and its lowest note separately, and reproduce a five-note bass line.',
      beforeYouStart: 'Follows Module 8. C major, 60 BPM, with a bass-focused playback mix. This is a controlled introduction; real recordings are less clear than this.',
      skills: ['chord-hearing'],
      glossary: ['root-and-bass', 'inversion'],
      blocks: [
        prose(
          undefined,
          'You met the distinction in Module 5 while playing. Now you will hear it. The chord identity can stay the same while the bass moves underneath it.',
        ),
        example('ex-m09-l01-a', 'C/E – F – C/G – G – C with the bass brought forward in the mix.'),
        prose(
          'Understand',
          'Three of these five chords are C major. What changes is the note underneath: E, then G, then C. Written out, they are C/E, C/G and C.',
          'Sing the bass line on its own: E–F–G–G–C. Notice it moves mostly by step, which is why this progression sounds smooth even though the chords above it are repeating.',
          'If listening to the inner voices distracts you, solo the bass in the mix, learn the line, then restore the full chords and find it again inside the texture.',
          'One honest caveat: in real recordings the lowest audible note can be masked by other instruments, by the room, or by your speakers. This exercise gives you a clean version so the skill can start somewhere reliable.',
        ),
        example('ex-m09-l01-b', 'The bass line alone: E–F–G–G–C. Sing it, then find it at the piano.'),
        exercise('q-m09-l01'),
        pianoTask(
          [
            'Play the five chords with the melody removed.',
            'Play the bass line alone and sing it.',
            'For C/E, say "root C, bass E" out loud.',
            'Put the voicings back together and follow the bass by ear.',
          ],
          'If inner voices distract you, solo the bass first, then restore the chords.',
          'Invent your own stepwise bass line under a repeated C chord.',
        ),
        reflection('Was it easier to hear the bass when the chords were full, or when it was soloed?'),
      ],
      makeItYours: 'Take a progression you already play and move one chord to first inversion so the bass line steps instead of leaping.',
      ifDifficult: [
        'If listening to inner voices distracts, solo the bass, then restore chords.',
        'Sing the bass line before trying to identify anything.',
        'Say root and bass as two separate words every time.',
      ],
      readinessCheck: 'Can you identify root C and bass E for C/E, and reproduce the five-note bass line?',
      takeaway: 'The chord is named by its root; the bass line has a shape of its own.',
      reviewTask: 'Name the bass note of one chord played with a bass-focused mix.',
      reviewExerciseId: 'q-m09-l01',
    },
    {
      id: 'm09-l02',
      title: 'Harmonic rhythm and non-chord tones',
      objective: 'Explain why not every melody note needs a chord, and choose a slower harmonic rhythm for a phrase.',
      beforeYouStart: 'Follows m09-l01. C major, 60 BPM. Both versions of each example are played at the same tempo so the comparison is fair.',
      skills: ['harmonization'],
      glossary: ['harmonic-rhythm', 'non-chord-tone'],
      blocks: [
        prose(
          undefined,
          'Harmonic rhythm is how often the chords change. It is a choice, and one that shapes a phrase as much as the chords themselves do.',
        ),
        example('ex-m09-l02-a', 'E–F–G over one held C chord. The F is brief.'),
        example('ex-m09-l02-b', 'The same melody with a chord change on the F. Listen at the same tempo and compare.'),
        prose(
          'Understand',
          'In the first version, F is a passing note: it connects two chord tones, E and G, and it does not last long enough to demand its own harmony. In the second version, a chord change tracks it. Neither is wrong; they produce different effects.',
          'Chord-tone membership is a clue, not a rule. If you treat "this note is not in the chord" as an error, you will end up changing chords on every beat and the phrase will sound restless.',
          'Duration and position change the picture though. Hold F for two beats instead of a fraction of one, and giving it its own harmony becomes far more attractive. Hear both versions of that too, at the same tempo, and notice that your preference changed with the duration.',
        ),
        example('ex-m09-l02-c', 'A sustained F over C, then the same bar over F. Now the duration is doing the arguing.'),
        exercise('q-m09-l02'),
        pianoTask(
          [
            'Play E–F–G over a held C chord.',
            'Play it again changing to F on the second beat.',
            'Hold the F for two beats and compare both harmonizations once more.',
            'Choose a slower harmonic rhythm for a four-bar phrase and play it.',
          ],
          'If you are treating chord-tone membership as a rule, hear both versions at the same tempo and describe the difference in words.',
          'Take a phrase you harmonized in Module 4 and halve its harmonic rhythm.',
        ),
        reflection('Which version of the sustained-F bar did you prefer, and did duration change your mind?'),
      ],
      makeItYours: 'Take one of your own four-bar phrases and rewrite its chart with half as many chord changes. Play both and keep one.',
      ifDifficult: [
        'If you treat chord-tone membership as a rule, hear both versions at one tempo and discuss the effect.',
        'Start with one chord per two bars and add changes only where you miss them.',
        'Remember not every accented note has to be a chord tone.',
      ],
      readinessCheck: 'Can you explain why every melody note does not require a new chord, and choose a slower harmonic rhythm for a phrase?',
      takeaway: 'Fewer chord changes often make a phrase clearer, not poorer.',
      reviewTask: 'Compare one bar with one chord and with two, and choose.',
      reviewExerciseId: 'q-m09-l02',
    },
    {
      id: 'm09-l03',
      title: 'ii and V7',
      objective: 'Play Dm–G7–C slowly and identify the seventh of G7.',
      beforeYouStart: 'Follows m09-l02. C major, 60 BPM. G7 may be reduced to three notes if four is uncomfortable.',
      skills: ['chord-hearing', 'harmonization'],
      glossary: ['dominant-seventh', 'roman-numeral', 'tonic-predominant-dominant'],
      blocks: [
        prose(
          undefined,
          'Two additions sharpen a cadence considerably. D minor is ii, a predominant chord that leads towards the dominant. G7 is V7, a dominant triad with a seventh added.',
        ),
        example('ex-m09-l03-a', 'Dm–G7–C with a melody. Listen twice before reading further.'),
        prose(
          'Understand',
          'The chords are D–F–A, then G–B–D–F, then C–E–G. G7 is a major triad plus a minor seventh above its root; that seventh is F.',
          'Two voices do the work at the change. F moves down to E, and B moves up to C. Play just those two notes moving while a C bass sounds, and the pull becomes obvious.',
          'If four notes feel like too much, there are two reductions that keep the character: omit the fifth D from G7, or play a G bass in the left hand with just B and F above it. Both are normal voicings, not compromises.',
          'A caution about scope: this is one common resolution in one common style. Other styles voice and resolve sevenths differently, and V7 does not always have to resolve to I at all.',
        ),
        exercise('q-m09-l03'),
        pianoTask(
          [
            'Play D–F–A, then G–B–D–F, then C–E–G, slowly.',
            'Play only F moving to E, and B moving to C, over a C bass.',
            'Accompany the example melody with the three chords.',
            'Say which note is the seventh of G7.',
          ],
          'If four notes feel difficult, omit the fifth D from G7 or play a bass plus B and F.',
          'Add ii–V7–I to the end of a phrase you already play.',
        ),
        reflection('Could you hear the F falling to E inside the chord change, or only the chords as blocks?'),
      ],
      makeItYours: 'Replace a plain G–C ending in one of your own phrases with Dm–G7–C. Decide whether you prefer it there.',
      ifDifficult: [
        'If four notes feel difficult, omit the fifth D from G7 or play bass plus B and F.',
        'Practise only the two moving voices before playing full chords.',
        'Do not assume every V7 uses this voicing or this resolution.',
      ],
      readinessCheck: 'Can you play the progression slowly and identify G7’s seventh, F?',
      takeaway: 'The seventh adds a second voice that wants to move.',
      reviewTask: 'Play Dm–G7–C and name the seventh.',
      reviewExerciseId: 'q-m09-l03',
    },
    {
      id: 'm09-l04',
      title: 'Compare two arrangements',
      objective: 'Choose between two harmonizations of the same melody with an audible reason, and play the roots of your choice.',
      beforeYouStart: 'Follows m09-l03. First Light bars 5–8, C major, 4/4, 60 BPM. Tempo and melody volume stay identical across both versions.',
      skills: ['harmonization', 'arranging'],
      glossary: ['harmonic-rhythm', 'root-and-bass', 'lead-sheet'],
      blocks: [
        prose(
          undefined,
          'Everything in this module comes together here. The same four bars, two harmonizations, one honest comparison.',
        ),
        example('ex-m09-l04-a', 'Version A: F–C–G–C. The version you met in Module 4.'),
        example('ex-m09-l04-b', 'Version B: Dm–Am–G7–C. Same melody, same tempo, same melody volume.'),
        prose(
          'Understand',
          'Compare three specific things rather than forming a vague impression. First, bass direction: F–C–G–C leaps, while D–A–G–C moves differently and sets up the final step. Second, phrase tension: G7 in version B pulls harder into the last bar. Third, the ending itself, which is the same chord reached by two different routes.',
          'If both sound fine to you, that is a valid result and worth recording as such. The Harmony Lab stores alternatives; it does not award correctness for matching a preset, and there is no "best chord" button anywhere in this app because there is no such thing.',
          'Optionally, try C/E for the second bar instead of plain C. Name the root and the bass separately when you record it, as you practised in lesson 1 of this module.',
        ),
        exercise('q-m09-l04'),
        pianoTask(
          [
            'Play version A with roots only under the melody.',
            'Play version B with roots only.',
            'Choose one and state an audible reason out loud.',
            'Play the roots of your chosen version while singing the melody.',
          ],
          'If both sound fine, record that as your result — it is a legitimate outcome.',
          'Try C/E in bar 6 and name its root and bass separately.',
        ),
        reflection('What exactly did you hear that made you prefer one version? Bass direction, tension, or ending?'),
      ],
      makeItYours: 'Save both arrangements in the Harmony Lab with your written reason, so you can hear them again after Module 12.',
      ifDifficult: [
        'If both sound fine, that is a valid result.',
        'Compare bass lines alone before comparing full arrangements.',
        'Keep tempo and melody volume identical so the comparison stays fair.',
      ],
      readinessCheck: 'Can you select a preference with an audible reason and play its roots under the melody?',
      takeaway: 'Compare specific features, not general impressions.',
      reviewTask: 'Play the bass line of two harmonizations and choose one.',
      reviewExerciseId: 'q-m09-l04',
    },
  ],
);
