import { example, exercise, makeModule, pianoTask, prose, reflection } from './builder';

export const module07 = makeModule(
  'm07',
  7,
  'Minor keys and expressive colour',
  'Establish a minor tonic, meet the raised seventh, and arrange a minor melody of your own.',
  [
    {
      id: 'm07-l01',
      title: 'Hear A as home',
      objective: 'Distinguish an established C-major centre from an established A-minor centre using the same seven notes.',
      beforeYouStart: 'Follows Module 6. C major and A minor, 58–60 BPM. Both use the white keys; context decides which note is home.',
      skills: ['tonal-center'],
      glossary: ['natural-minor', 'relative-parallel'],
      blocks: [
        prose(
          undefined,
          'C major and A natural minor contain exactly the same seven pitch classes. What separates them is not the notes; it is which note the music keeps returning to.',
        ),
        example('ex-m07-l01-a', 'A C-major cadence: F–G–C. Sing the note that feels settled.'),
        example('ex-m07-l01-b', 'Am–Dm–Em–Am. Same white keys. Now sing the note that feels settled.'),
        prose(
          'Understand',
          'Describing minor as "the major scale started on a different note" is true about the collection and misleading about the music. It skips the part that actually creates a minor key: a context that keeps arriving on A.',
          'Listen to the two examples back to back. In the first, C is the arrival. In the second, A is. If the shared notes confuse you, hold an A in the bass and finish every attempt on A — a drone makes the centre unmistakable.',
          'Then hear the study Evening Window, which is in A minor throughout. Sing A as home and play A–C–E–C–A so the tonic triad is in your hand as well as your ear.',
        ),
        example('ex-m07-l01-c', 'Evening Window establishes A as home. Find its first two bars by ear.', true),
        exercise('q-m07-l01'),
        pianoTask(
          [
            'Play F–G–C and sing the home note.',
            'Play Am–Dm–Em–Am and sing the home note.',
            'Play A–C–E–C–A with a held A bass.',
            'Find the first two bars of Evening Window by ear.',
          ],
          'If the shared notes confuse you, hold an A bass throughout and finish on A every time.',
          'Establish E minor with Em–Am–Bm–Em and find its home note the same way.',
        ),
        reflection('Which contextual clue told you the centre had moved — the chords, the bass, or the final note?'),
      ],
      makeItYours: 'Play a short phrase on the white keys twice: once ending over C, once ending over Am. Describe the difference in one sentence.',
      ifDifficult: [
        'If the shared notes confuse you, hold an A bass and finish on A.',
        'Play the two progressions immediately after each other, never separately.',
        'Do not rely on the idea that minor is just the C scale started elsewhere; establish context every time.',
      ],
      readinessCheck: 'Can you distinguish the established home in four contextual examples, and find Evening Window’s first two bars?',
      takeaway: 'The centre comes from context, not from the collection of notes.',
      reviewTask: 'Hear one progression and say whether home is C or A.',
      reviewExerciseId: 'q-m07-l01',
    },
    {
      id: 'm07-l02',
      title: 'The raised seventh in minor',
      objective: 'Hear and play the difference between Em–Am and E–Am, and identify the raised seventh in A minor.',
      beforeYouStart: 'Follows m07-l01. A minor, 58 BPM. One note changes between the two progressions: G becomes G#.',
      skills: ['chord-hearing', 'tonal-center'],
      glossary: ['harmonic-minor', 'roman-numeral'],
      blocks: [
        prose(
          undefined,
          'In A natural minor the chord on degree 5 is E minor: E–G–B. Raise that G to G# and you get E major: E–G#–B. One semitone changes how strongly the chord points home.',
        ),
        example('ex-m07-l02-a', 'Em–Am, then E–Am. Listen for the single note that differs.'),
        prose(
          'Understand',
          'G# is the raised seventh degree of A minor. It sits a semitone below A, which is exactly the relationship that makes degree 7 lean so strongly in major keys. Natural minor does not have that semitone; harmonic minor supplies it.',
          'Sing G#–A on its own before you play the phrase. If G# feels like a mistake at first, that is common — isolate G#–A over the E–Am pair until it sounds intentional, then return to the melody.',
          'Harmonic minor is a useful collection, not a replacement for natural minor. Real minor-key music moves between them, and a natural G can appear elsewhere in the same piece without being an error. Spell the note G#, never Ab; the spelling reflects its function as a raised seventh.',
        ),
        example('ex-m07-l02-b', 'B4–G#4–E4 over E, then A4 over Am. The phrase arrives because of that G#.'),
        exercise('q-m07-l02'),
        pianoTask(
          [
            'Play Em then Am. Play E then Am. Say which note changed.',
            'Sing G#–A five times with an A bass sounding.',
            'Play the example phrase over E, then resolve to A.',
          ],
          'If G# feels like a mistake, isolate G#–A over E–Am before returning to the phrase.',
          'Find another minor-key progression that uses the raised seventh and play it.',
        ),
        reflection('Did the E major version feel stronger, or just different? Both answers are legitimate.'),
      ],
      makeItYours: 'Write a two-bar phrase in A minor that touches G# once and ends on A. Play it with both Em and E underneath and choose.',
      ifDifficult: [
        'If G# feels like a mistake, isolate G#–A over E–Am first.',
        'Play the two chords with a held A bass so the pull is obvious.',
        'Remember natural G still belongs in A minor elsewhere; this is a local alteration.',
      ],
      readinessCheck: 'Can you hear and play the difference between Em–Am and E–Am, and identify the raised seventh in A minor?',
      takeaway: 'The raised seventh supplies the semitone that makes V point home.',
      reviewTask: 'Identify whether a chord before Am was Em or E major.',
      reviewExerciseId: 'q-m07-l02',
    },
    {
      id: 'm07-l03',
      title: 'Minor progressions and alternatives',
      objective: 'Play two contrasting minor progressions and invent a two-bar melody over one of them.',
      beforeYouStart: 'Follows m07-l02. A minor, 58 BPM. Roman numerals and chord names are always shown together, never one instead of the other.',
      skills: ['chord-hearing', 'harmonization', 'improvisation'],
      glossary: ['roman-numeral', 'tonic-predominant-dominant'],
      blocks: [
        prose(
          undefined,
          'Two loops cover most of what you need in minor keys. Am–F–C–G stays open and never uses the raised seventh. Am–Dm–E–Am returns firmly through E.',
        ),
        example('ex-m07-l03-a', 'Am–F–C–G, that is i–VI–III–VII. Notice it does not close.'),
        example('ex-m07-l03-b', 'Am–Dm–E–Am, that is i–iv–V–i. Notice the arrival.'),
        prose(
          'Understand',
          'Play both with bass roots first, then with compact chords. Listen specifically to the last chord of each: the first loop leaves you somewhere else and invites a repeat; the second brings you home.',
          'Now a listening experiment. Hold C5 as a sustained melody note over Am and then over F. In Am, C is the third of the chord. In F, C is the fifth. The note has not changed and its role has.',
          'If chord symbols start to feel overwhelming, look at the numerals and the names together — i–VI–III–VII alongside Am–F–C–G. The app never replaces one with the other invisibly, because knowing both is what lets you move this progression to another key later.',
        ),
        example('ex-m07-l03-c', 'A sustained C5 over Am, then over F. Same note, different role.'),
        exercise('q-m07-l03'),
        pianoTask(
          [
            'Play Am–F–C–G with bass roots, then compact chords.',
            'Play Am–Dm–E–Am the same way.',
            'Hold C5 over Am and over F and name its role in each.',
            'Invent a two-bar melody over one of the two loops.',
          ],
          'If the symbols are overwhelming, display numerals and note names together and read both.',
          'Play the first loop four times and improvise a continuous melody across the repeats.',
        ),
        reflection('Which loop suits the kind of music you would like to play? Note it for Module 10.'),
      ],
      makeItYours: 'Choose one loop and improvise over it for two minutes without stopping. Then play the single best two-bar idea you found.',
      ifDifficult: [
        'If the chord symbols are overwhelming, use numerals and names side by side.',
        'Use bass roots only until the shape of each loop is memorable.',
        'Work with one loop per session rather than both.',
      ],
      readinessCheck: 'Can you play both progressions and invent a two-bar melody over one?',
      takeaway: 'One minor loop stays open; the other closes. Choose deliberately.',
      reviewTask: 'Play one minor progression from its Roman numerals.',
      reviewExerciseId: 'q-m07-l03',
    },
    {
      id: 'm07-l04',
      title: 'Arrange a minor melody',
      objective: 'Play four connected bars of Evening Window with an accompaniment and explain why G# occurs.',
      beforeYouStart: 'Follows m07-l03. Evening Window (S03), A minor, 4/4, 58 BPM. Learn it by ear in two-bar chunks.',
      skills: ['arranging', 'harmonization', 'accompaniment'],
      glossary: ['harmonic-minor', 'arpeggio'],
      blocks: [
        prose(
          undefined,
          'This lesson brings the module together: a minor melody found by ear, supported by its own harmony, with the raised seventh in its proper place.',
        ),
        example('ex-m07-l01-c', 'Evening Window bars 1–2. Learn this chunk before you look at anything else.', true),
        prose(
          'Understand',
          'Find the melody in two-bar chunks, exactly as in Module 3. Then add bass roots only: Am, Dm, E, Am for the first four bars. Only when the roots are secure should you add compact broken chords.',
          'Watch for G# at the E chords in bars 3 and 7. It is not an accident of the scale; it is the raised seventh that makes E major work as V, and the melody uses it right before arriving on A.',
          'The final cadence is E–Am. Compare it with Em–Am and save what you hear. Do not record one as universally better — the two produce different degrees of pull, and different pieces want different amounts of it.',
        ),
        exercise('q-m07-l04'),
        pianoTask(
          [
            'Find bars 1–2 by ear, then bars 3–4.',
            'Add bass roots Am, Dm, E, Am under those four bars.',
            'Add compact broken chords once the roots are comfortable.',
            'Play four connected bars and say out loud why G# appears.',
          ],
          'If the right hand loses the altered note, practise only bars 3–4 and 7–8 with left-hand roots.',
          'Complete all eight bars with an accompaniment pattern of your choice.',
        ),
        reflection('Compare the final E–Am with Em–Am. Write one observation, not a verdict.'),
      ],
      makeItYours: 'Choose an accompaniment pattern for Evening Window and save it as an arrangement with a one-sentence reason.',
      ifDifficult: [
        'If the right hand loses the altered note, practise only bars 3–4 and 7–8 with left-hand roots.',
        'Play bass roots alone under the whole melody before adding anything else.',
        'Four connected bars is the target; all eight is the stretch task.',
      ],
      readinessCheck: 'Can you play four connected bars and explain why G# occurs?',
      takeaway: 'A minor arrangement is the same process as a major one, plus one deliberate alteration.',
      reviewTask: 'Play two bars of Evening Window with bass roots.',
      reviewExerciseId: 'q-m07-l04',
    },
  ],
);
