import { example, exercise, makeModule, pianoTask, prose, reflection } from './builder';

export const module03 = makeModule(
  'm03',
  3,
  'Rhythm and phrase memory',
  'Keep a pulse while the notes change, use silence on purpose, and hold longer phrases in your ear.',
  [
    {
      id: 'm03-l01',
      title: 'Keep the pulse while notes change',
      objective: 'Maintain a steady pulse through held notes and apply two different rhythms to the same three pitches.',
      beforeYouStart: 'Follows Module 2. C major, 4/4, 60 BPM with a one-bar count-in. Clapping is as valid as tapping the screen.',
      skills: ['rhythm'],
      glossary: ['compound-meter'],
      blocks: [
        prose(
          undefined,
          'Beat and note onset are different things. The pulse continues underneath whether or not a new note starts, and a long note simply spans several beats of that continuing pulse.',
        ),
        example('ex-m03-l01-a', 'Three notes with durations 1, 1, 2. Count the beats out loud through the last note.'),
        example('ex-m03-l01-b', 'Now durations 0.5, 0.5, 1, 2 on C–D–E–G. The pulse has not changed; only the note starts have.'),
        prose(
          'Understand',
          'At 60 beats per minute each quarter note lasts one second, which is slow enough to count comfortably. Clap the first rhythm — one, one, two — and keep counting "3, 4" silently through the held note. Then clap the second rhythm, where two eighth notes share a single beat.',
          'Apply both rhythms to the same three pitches, C–D–E. Hearing one set of notes carry two different rhythms is the clearest demonstration that rhythm is a separate layer you can choose.',
          'Use the count-in, then play four bars with the metronome. If your screen taps feel late, that is worth separating from the musical question: interface and audio delay are real, and they are not the same thing as rushing or dragging. Clap without a score if you want to remove that variable entirely.',
        ),
        exercise('q-m03-l01'),
        pianoTask(
          [
            'Start the metronome at 60 with a one-bar count-in.',
            'Clap rhythm one for four bars, keeping the pulse through every held note.',
            'Clap rhythm two for four bars.',
            'Play C–D–E with rhythm one, then with rhythm two, at the piano.',
          ],
          'Slow the metronome to 45 BPM and use only the first rhythm.',
          'Try both rhythms at 72 BPM without losing evenness.',
        ),
        reflection('Did you rush or drag through the held note? Which direction, and by how much, as best you can tell?'),
      ],
      makeItYours: 'Take any three-note phrase you already know and give it a new rhythm. Play the old and new versions back to back so the difference is obvious.',
      ifDifficult: [
        'If tapping the screen feels late, distinguish interface delay from the musical task; clap without a score instead.',
        'Slow to 45 BPM if that helps you keep the pulse audible.',
        'Count out loud. Silent counting is harder than it looks.',
      ],
      readinessCheck: 'Can you maintain the pulse through held notes in two short attempts, self-assessed at the piano?',
      takeaway: 'The pulse keeps going whether or not a new note begins.',
      reviewTask: 'Clap one rhythm containing a held note after a count-in.',
      reviewExerciseId: 'q-m03-l01',
    },
    {
      id: 'm03-l02',
      title: 'Rests, pickups, and repeated notes',
      objective: 'Reproduce a rest without filling it, and enter correctly after a one-beat pickup.',
      beforeYouStart: 'Follows m03-l01. C major, 4/4, 60 BPM. One example deliberately begins before the first complete bar.',
      skills: ['rhythm', 'phrase-memory'],
      glossary: ['pickup'],
      blocks: [
        prose(
          undefined,
          'Silence is part of a phrase, not an absence of one. A rest has a duration, it occupies the pulse, and removing it changes the music as much as changing a pitch would.',
        ),
        example('ex-m03-l02-a', 'A phrase with a rest on beat 2. Clap it before you try to play it.'),
        example('ex-m03-l02-b', 'The same four beats with a repeated note instead of the rest. Compare the two directly.'),
        prose(
          'Understand',
          'Play the two examples one after the other. The pitches are nearly identical; what differs is whether beat 2 contains a sound or a silence. Many people fill rests automatically, so the exercise is to leave the gap intentionally.',
          'Next, a pickup. A pickup is one or more notes that arrive before the first complete bar. The example below has a single quarter-note G4 leading into a full bar of C5–B4–A4. The G does not belong to bar 1; it belongs in front of it.',
          'Clap the rhythm first and find the pitches second. If counting the pickup is confusing, clap the strong first beat of the bar while the app plays the pickup note, so you feel where the downbeat lands.',
        ),
        example('ex-m03-l02-c', 'A one-beat pickup leading into a complete bar. The pickup is shown separately from bar 1.'),
        exercise('q-m03-l02'),
        pianoTask(
          [
            'Clap the rest example four times, leaving beat 2 genuinely silent.',
            'Play both examples at the piano and listen for the difference.',
            'Count "4" out loud, then play the pickup note on that beat and continue into the bar.',
          ],
          'If pickup counting is confusing, clap the downbeat while the app plays the pickup note.',
          'Write your own two-bar phrase with one rest and one pickup, then play it.',
        ),
        reflection('Did you fill the rest on your first attempt? Most people do at least once.'),
      ],
      makeItYours: 'Take a phrase you already play and remove one note, leaving a rest in its place. Decide whether you prefer the phrase with or without that note.',
      ifDifficult: [
        'If pickup counting is confusing, clap the strong first beat while the app plays the pickup.',
        'Say "rest" out loud where the silence falls.',
        'Practise the rhythm on one repeated pitch before adding the melody.',
      ],
      readinessCheck: 'Can you reproduce a rest without inserting a note, and enter correctly after a count-in?',
      takeaway: 'A rest is a duration you play, not a gap you fall into.',
      reviewTask: 'Clap one rhythm that contains a rest, without filling it.',
      reviewExerciseId: 'q-m03-l02',
    },
    {
      id: 'm03-l03',
      title: 'Hear pairs of phrases',
      objective: 'Assemble a four-bar phrase from two-bar chunks and describe which ending feels more settled.',
      beforeYouStart: 'Follows m03-l02. Uses the included study First Light (S01), C major, 4/4, 60 BPM. Work with one chunk at a time; the complete score is never revealed automatically.',
      skills: ['phrase-memory', 'tonal-center'],
      glossary: ['phrase', 'cadence'],
      blocks: [
        prose(
          undefined,
          'Melodies usually come in pairs. Something is stated, and something answers it. Once you hear that, four or eight bars stop being a long list of notes and become two or four objects.',
        ),
        example('ex-m03-l03-q', 'Bars 1–4 of First Light — the question. Listen to one two-bar chunk at a time, sing it, then assemble the phrase.'),
        prose(
          'Understand',
          'Take bars 1–2 alone. Listen, sing, and only then play. Then bars 3–4 the same way. Now join them, and notice how much less work the joined version is than learning four bars from scratch.',
          'Next, bars 5–8. Listen for material you have already heard: the answer reuses shapes from the question but its ending is different. Recognising repeated material is the single biggest shortcut in playing by ear.',
          'Then make a judgement. Which of the two endings feels more settled, and can you say why? Bars 1–4 end on G over dominant harmony; bars 5–8 end on C. You met that difference in Module 2, and here it is inside a real melody.',
        ),
        example('ex-m03-l03-a', 'Bars 5–8 — the answer. What does it reuse, and what does it change?', true),
        exercise('q-m03-l03'),
        pianoTask(
          [
            'Learn bars 1–2 by ear, then bars 3–4, then join them.',
            'Play the four bars from memory, allowing yourself one restart.',
            'Describe out loud which ending feels more settled and why.',
          ],
          'If all eight bars overload your memory, keep only the first and last two bars.',
          'Learn bars 5–8 as well and play all eight with one restart allowed.',
        ),
        reflection('What material is shared between the question and the answer? Name one specific thing.'),
      ],
      makeItYours: 'Play bars 1–2 of the study, then invent your own two-bar answer instead of the printed one. Keep one thing from the question and change the ending.',
      ifDifficult: [
        'If all eight bars overload your memory, retain only the first and last two bars.',
        'Ask for a hint on one chunk at a time; requesting help on bars 1–2 does not reveal the rest.',
        'Sing each chunk before you play it, every time.',
      ],
      readinessCheck: 'Can you play four bars from memory with one restart allowed, and describe which ending feels more settled?',
      takeaway: 'Learn in chunks and look for what repeats.',
      reviewTask: 'Reconstruct one two-bar chunk of First Light by ear.',
      reviewExerciseId: 'q-m03-l03',
    },
    {
      id: 'm03-l04',
      title: 'Recover a familiar tune',
      objective: 'Recover a recognisable four-to-eight-bar melody by ear and identify where you were uncertain.',
      beforeYouStart: 'Follows m03-l03. Choose a tune you can already sing from memory, or use First Light as the included alternative. Any key; start wherever is comfortable.',
      skills: ['pitch-mapping', 'phrase-memory', 'inner-hearing'],
      glossary: ['contour', 'phrase'],
      blocks: [
        prose(
          undefined,
          'This is the first lesson where the source is yours rather than the app\'s. Choose a tune you can sing without help — a folk song, a hymn, something from a film you have watched many times. The app does not need a recording or a score of it, and saving its title here does not add anyone else\'s music to this course.',
        ),
        prose(
          'Understand',
          'Work in a fixed order. First sing one phrase, all the way through, so the target is in your ear rather than in your fingers. Second, find a comfortable starting note — any note; you are not obliged to find the original key. Third, map the contour: where does it rise, fall, repeat, leap? Fourth, recover the rhythm by clapping it. Only then join the chunks into a phrase.',
          'Separate two different difficulties as you go. Forgetting how the tune goes is one problem, and finding its notes on the keyboard is another. If you cannot sing it from memory, the tune is not ready — switch to the included study and come back later.',
          'Expect one or two uncertain spots. Note where they are rather than smoothing over them; naming your own uncertainty accurately is a skill this course returns to in Module 12.',
        ),
        example('ex-m03-l03-q', 'The included alternative: First Light bars 1–4, if you would rather not choose your own tune today.'),
        exercise('q-m03-l04'),
        pianoTask(
          [
            'Sing one phrase of your chosen tune all the way through.',
            'Find a comfortable starting note and map the contour without playing.',
            'Clap the rhythm, then find the pitches in two- or three-note chunks.',
            'Join the chunks and play four to eight bars with the notes hidden.',
          ],
          'If the tune cannot be sung from memory, use First Light instead and transfer the process later.',
          'Recover a second phrase of the same tune and join it to the first.',
        ),
        reflection('Where exactly were you uncertain — a particular interval, a rhythm, or a whole bar? Name the spot.'),
      ],
      makeItYours: 'Give your recovered melody a title in the notebook and record one sentence about how you found it. The title is yours; the course content stays original.',
      ifDifficult: [
        'If the tune cannot be sung from memory, use the included study first.',
        'Separate forgetting the tune from difficulty finding its notes — they need different remedies.',
        'Shorten to a single phrase and stop there; a recovered phrase is a real result.',
      ],
      readinessCheck: 'Can you recover a recognisable four-to-eight-bar melody with notes hidden, and note one uncertain spot?',
      takeaway: 'Sing first, map the shape, recover the rhythm, then find the notes.',
      reviewTask: 'Recover two bars of a tune you can sing, without looking at notation.',
      reviewExerciseId: 'q-m03-l04',
    },
  ],
);
