import { example, exercise, makeModule, pianoTask, prose, reflection } from './builder';

export const module02 = makeModule(
  'm02',
  2,
  'Hear a home note and scale degrees',
  'Find the note a phrase is leaning towards, and name the notes around it by their position in the key.',
  [
    {
      id: 'm02-l01',
      title: 'Find home',
      objective: 'Identify the tonic of a short phrase from its context, and notice when a phrase deliberately ends somewhere else.',
      beforeYouStart: 'Follows Module 1. C major and then G major, 60 BPM. A tonic reference is always supplied; you are never asked to name a note out of silence.',
      skills: ['tonal-center'],
      glossary: ['scale-degree', 'cadence', 'tonic-predominant-dominant'],
      blocks: [
        prose(
          undefined,
          'A tonal centre is not a property of one note. It comes from context: the chords around a phrase, the notes that keep returning, the place the music seems to want to rest.',
        ),
        example('ex-m02-l01-key', 'C–F–G–C. Four chords are enough to make C feel like home. Listen twice.'),
        prose(
          'Understand',
          'After those chords, C is no longer just a letter. It is the place the music settles. Sing it, and notice that it feels like an arrival rather than a step on the way somewhere.',
          'Now the interesting part. A phrase can end on a note that is not home, and that is a normal musical choice rather than a mistake. The three phrases below end on C, on D, and on B. Only one of them is settled; the other two lean forward.',
          'This is why the last note of a melody is not proof of its key. Sing the note that would make each phrase feel finished, then compare your sung note with C.',
        ),
        example('ex-m02-l01-a', 'Phrase one. Sing the note that would make it feel settled, then compare with the note it actually ends on.'),
        example('ex-m02-l01-b', 'Phrase two. Does it arrive, or does it lean?', true),
        example('ex-m02-l01-c', 'Phrase three. Same question. Which way does it lean — up or down?', true),
        exercise('q-m02-l01'),
        example('ex-m02-l01-g', 'The same idea in G major: G–C–D–G. Home has moved, and nothing else about the process changed.'),
        pianoTask(
          [
            'Play C–F–G–C slowly in your left hand, using single bass notes if chords are awkward.',
            'Sing C afterwards and hold it until it feels stable.',
            'Repeat with G–C–D–G and sing G. Notice you did exactly the same thing in a new key.',
          ],
          'If the last melody note keeps being mistaken for home, play B–C and then D–C over a final C chord and listen to both resolutions.',
          'Establish F major with F–Bb–C–F and find its home note by ear.',
        ),
        reflection('Which of the three phrases felt most unfinished, and can you say why in one sentence?'),
      ],
      makeItYours: 'Play any four notes you like in C major, then finish the phrase on C. Play the same four notes again and finish on D instead. Say out loud which one you would use to end a piece.',
      ifDifficult: [
        'If the last melody note keeps being mistaken for home, hear B–C and D–C over the final C chord and compare.',
        'Hold a C bass note under the whole phrase while you listen.',
        'Avoid testing yourself on isolated notes with no context; that is a different and much harder skill.',
      ],
      readinessCheck: 'Can you find the tonic after four of five contextual examples, with a supplied tonic reference allowed?',
      takeaway: 'Home comes from context, and a phrase is allowed to end away from it.',
      reviewTask: 'Hear one progression and one phrase, then sing the note that would settle it.',
      reviewExerciseId: 'q-m02-l01',
    },
    {
      id: 'm02-l02',
      title: 'Anchor degrees 1, 3, and 5',
      objective: 'Recognise and play degrees 1, 3 and 5 in a key after a tonic reference, in C and in G.',
      beforeYouStart: 'Follows m02-l01. C major then G major, 60 BPM. Degrees are positions in the key, used alongside note names rather than instead of them.',
      skills: ['tonal-center', 'pitch-mapping'],
      glossary: ['scale-degree', 'triad'],
      blocks: [
        prose(
          undefined,
          'Degrees give you a language that survives a change of key. Degree 1 is the tonic, degree 3 is two scale notes above it, degree 5 two above that. In C major those are C, E and G — the notes of the C chord you already played in Module 1.',
        ),
        example('ex-m02-l02-a', 'Sing along: 1–3–5–3–1 over a C chord. Hear it before you look at any labels.'),
        prose(
          'Understand',
          'These three degrees are anchors because they are stable. Land on any of them and the phrase can rest there for a moment without sounding unfinished.',
          'Practise three-note combinations drawn from the anchors: 1–3–1, then 1–5–3, then 3–5–1. Hear each one before you view the degrees. When you check, check the whole group rather than one note.',
          'One caution for later: degree 3 becomes a lowered third in minor keys. In A minor, C is b3 rather than 3. We will deal with that properly in Module 7; for now, everything is major.',
        ),
        exercise('q-m02-l02'),
        example('ex-m02-l02-b', 'The same relationships in G major: G–B–D. The degrees are identical; only the letters changed.'),
        pianoTask(
          [
            'Play a C chord, then sing 1–3–5–3–1 and find it in the right hand.',
            'Echo three-note combinations: 1–3–1, 1–5–3, 3–5–1. Hear each before you check.',
            'Establish G major and play the same three relationships as G–B–D.',
          ],
          'If a five-note phrase is hard, keep the tonic sounding and work with pairs: 1–3, then 3–5, then 5–1.',
          'Move the same three degrees to F major and name the letters as you play.',
        ),
        reflection('When you moved to G, did you think in letters or in degrees? Either is fine today — notice which one you reached for.'),
      ],
      makeItYours: 'Make a five-note phrase using only degrees 1, 3 and 5, ending on 1. Play it in C, then play the same degrees in G without writing anything down.',
      ifDifficult: [
        'If a five-note phrase is hard, keep the tonic audible and work in pairs.',
        'Play the chord before every attempt so the anchors stay in your ear.',
        'Say the degree numbers out loud while you play them.',
      ],
      readinessCheck: 'Can you find four of five C-major examples and one G-major example after a tonic reference?',
      takeaway: 'Degrees 1, 3 and 5 are the stable places to land in any major key.',
      reviewTask: 'Hear one target note after a tonic reference and name its degree.',
      reviewExerciseId: 'q-m02-l02',
    },
    {
      id: 'm02-l03',
      title: 'Hear 2 and 4 through resolution',
      objective: 'Recognise degrees 2 and 4 by the way they lean towards the anchors around them.',
      beforeYouStart: 'Follows m02-l02. C major, 60 BPM. Degrees 1–5 only. A tonic reference precedes each prompt.',
      skills: ['tonal-center', 'inner-hearing'],
      glossary: ['scale-degree', 'non-chord-tone'],
      blocks: [
        prose(
          undefined,
          'Degrees 2 and 4 are harder to hear on their own because they are less stable — and that instability is exactly how you identify them. Each one gains meaning from the notes around it.',
        ),
        example('ex-m02-l03-a', '1–2–1, then 3–4–3. Listen for the lean and the return in each pair.'),
        prose(
          'Understand',
          'Degree 2 sits between 1 and 3. Sing 1–2–1 and you hear it fall back home; sing 1–2–3 and you hear it continue upward. In C major that is D, and D by itself has no strong identity — it borrows one from its neighbours.',
          'Degree 4 behaves similarly between 3 and 5. Sing 3–4–3 and then 5–4–3. In C that is F, and the descent 5–4–3 is one of the most recognisable small gestures in tonal music.',
          'Be careful with the word "resolution". These are contextual tendencies, not compulsory directions. Plenty of good music holds a degree 4 or walks it upward. What you are training is a probability your ear can lean on, not a law.',
        ),
        example('ex-m02-l03-b', '1–2–3, then 5–4–3. The same two notes, now continuing rather than returning.'),
        exercise('q-m02-l03'),
        pianoTask(
          [
            'Complete six short echoes using degrees 1 to 5, including repeated notes and descending movement.',
            'Hear each echo once, sing it, then play it — do not search key by key while the sound is still fresh.',
            'Invent one phrase of your own that uses degree 2 or 4 and ends on degree 1.',
          ],
          'If 2 and 4 blur together, return to their anchor resolutions — 1–2–1 and 3–4–3 — and compare them slowly, one after the other.',
          'Add degree 5 above and try 5–4–3–2–1 as one falling gesture.',
        ),
        reflection('Which lean is clearer to you right now: 2 falling to 1, or 4 falling to 3?'),
      ],
      makeItYours: 'Write a four-note phrase that passes through degree 4 on its way down to degree 1. Play it, then play a version that stops on degree 4 instead, and listen to the difference.',
      ifDifficult: [
        'If 2 and 4 blur together, go back to 1–2–1 and 3–4–3 and compare them slowly.',
        'Keep a tonic drone sounding underneath while you sing.',
        'Work with three-note groups only until the lean is obvious.',
      ],
      readinessCheck: 'Can you answer four of six echoes without visible notes, and invent one phrase ending on degree 1?',
      takeaway: 'Unstable degrees are recognised by where they want to go, not by their sound alone.',
      reviewTask: 'Name one target degree from 1–5 after a tonic reference.',
      reviewExerciseId: 'q-m02-l03',
    },
    {
      id: 'm02-l04',
      title: 'Complete the major scale',
      objective: 'Use degrees 6 and 7 inside short phrases and explain where home is in each one.',
      beforeYouStart: 'Follows m02-l03. C major, 60 BPM, with one transfer to G major. The scale is a reference collection here, not a drill.',
      skills: ['tonal-center', 'pitch-mapping'],
      glossary: ['major-scale', 'scale-degree'],
      blocks: [
        prose(
          undefined,
          'Two degrees remain. In C major, A is degree 6 and B is degree 7. Both are easiest to hear in motion rather than alone.',
        ),
        example('ex-m02-l04-a', 'G–A–B–C climbing, then B–A–G falling. Listen for the moment degree 7 arrives at the upper tonic.'),
        prose(
          'Understand',
          'Compare three small gestures. First 5–6–5: degree 6 steps away from the stable fifth and comes back. Then 7–1\': degree 7 sits one semitone below the upper tonic and pulls strongly towards it. Then 1\'–7–6–5: the same notes falling away from the top.',
          'Sing the full scale once so you know the collection. Then stop singing scales and practise short phrases instead. Scales tell you which notes exist; phrases teach your ear what they do.',
          'Notice that the step from degree 7 to degree 1 is a semitone, while 5 to 6 is a whole tone. This is the uneven spacing you met in Module 1, and it is why the same finger pattern does not transpose.',
        ),
        exercise('q-m02-l04'),
        example('ex-m02-l04-b', 'The same falling resolution in G major, which needs F# as its degree 7.'),
        pianoTask(
          [
            'Find a four-note phrase that contains degree 6 or 7, and say where home is.',
            'Play the last three notes of the example — the resolution back to the tonic — five times slowly.',
            'Transfer those three notes to G major, where degree 7 is F#.',
          ],
          'If 7–1 feels difficult to sing, drop to a comfortable lower octave and sing it there.',
          'Play the whole C major scale up and down, then improvise a four-bar phrase using any of its notes and ending on C.',
        ),
        reflection('In G major, did you find F# by ear, by the key signature, or by trial? All three are legitimate; note which you used.'),
      ],
      makeItYours: 'Invent a phrase that touches degree 7 and then resolves to the tonic. Play it in C, then move only the final three notes to G major.',
      ifDifficult: [
        'If 7–1 feels difficult vocally, use a comfortable lower octave.',
        'Approach degree 7 from below, through 5–6–7–1, rather than jumping to it.',
        'If the G-major transfer is confusing, sing the G scale once and listen for where the semitone falls.',
      ],
      readinessCheck: 'Can you find a four-note phrase containing degree 6 or 7 and explain where home is?',
      takeaway: 'Degree 7 leans hardest of all, and it is only a semitone from home.',
      reviewTask: 'Identify degree 6 or 7 in a short phrase after a tonic reference.',
      reviewExerciseId: 'q-m02-l04',
    },
  ],
);
