import { example, exercise, makeModule, pianoTask, prose, reflection } from './builder';

export const module06 = makeModule(
  'm06',
  6,
  'Improvise phrases with intention',
  'Invent a small idea on purpose, vary one thing at a time, and aim at notes you chose in advance.',
  [
    {
      id: 'm06-l01',
      title: 'Sing a motif before playing',
      objective: 'Invent and reproduce two short motifs of your own and identify where each one ends.',
      beforeYouStart: 'Follows Module 5. C major over a held C chord, 60 BPM. Use C, D, E, G and A in the right hand.',
      skills: ['improvisation', 'inner-hearing'],
      glossary: ['motif', 'pentatonic'],
      blocks: [
        prose(
          undefined,
          'A motif is a small recognisable idea — often three to five notes. It is short enough to hold in your ear, which is exactly why it makes a good first improvisation.',
        ),
        example('ex-m06-l01-a', 'A demonstration motif drawn from C, D, E, G and A, then answered. Yours will be different.'),
        prose(
          'Understand',
          'Hold a C chord and sing a three-to-five-note phrase using only C, D, E, G and A. Then find it on the piano and repeat it exactly. Repeating it is the difficult part and the important part.',
          'That five-note set is a major pentatonic collection: degrees 1, 2, 3, 5 and 6. It is convenient because it avoids the strongest leaning notes, which makes early improvisation forgiving. It is not a promise that every note in it is equally settled against every chord, and it is not a style you have to stay in.',
          'If your fingers run ahead of your ear, stop playing. Sing the idea again, then copy your own sung rhythm. Use silence between attempts rather than producing an endless stream of notes; the silence is where you decide what to play next.',
        ),
        exercise('q-m06-l01'),
        pianoTask(
          [
            'Hold a soft C chord in the left hand.',
            'Sing a three-to-five-note idea using C, D, E, G and A.',
            'Find it, play it, then play it again identically.',
            'Repeat with a second motif and say where each one ends.',
          ],
          'If fingers run ahead, stop playing entirely, sing again, then copy the sung rhythm.',
          'Invent a motif that ends on a note other than C and say what that ending does.',
        ),
        reflection('Could you repeat your first motif exactly, or did it change each time?'),
      ],
      makeItYours: 'Choose the motif you like best and give it a name. Play it at the start of your next three practice sessions before anything else.',
      ifDifficult: [
        'If fingers run ahead of your ear, stop playing, sing again, then copy the sung rhythm.',
        'Use silence between attempts instead of a continuous stream of notes.',
        'Limit yourself to three notes until repeating them exactly is easy.',
      ],
      readinessCheck: 'Can you reproduce two invented motifs and identify their endings?',
      takeaway: 'An improvisation you can repeat is an idea; one you cannot is an accident.',
      reviewTask: 'Invent one motif over a held chord and play it twice identically.',
      reviewExerciseId: 'q-m06-l01',
    },
    {
      id: 'm06-l02',
      title: 'Change one thing',
      objective: 'Produce three variants of one motif that stay recognisably connected to the original.',
      beforeYouStart: 'Follows m06-l01. C major, 60 BPM. The starting idea is C4–D4–E4 with durations 1, 1, 2.',
      skills: ['improvisation', 'rhythm'],
      glossary: ['motif', 'diatonic-sequence'],
      blocks: [
        prose(
          undefined,
          'Variation is how a short idea becomes a piece of music. The discipline is to change one thing at a time, so the connection to the original survives.',
        ),
        example('ex-m06-l02-a', 'The original idea: C–D–E, one beat, one beat, two beats.'),
        example('ex-m06-l02-b', 'Variation one: the rhythm changes, the pitches do not.'),
        example('ex-m06-l02-c', 'Variation two: the ending changes, the opening does not.'),
        prose(
          'Understand',
          'The three variations you will make are a rhythmic change, an ending change, and a sequence — the same shape starting one scale step higher.',
          'The sequence needs care. A diatonic sequence stays inside the key, so the exact intervals adjust: C–D–E becomes D–E–F, where the last step is a semitone rather than a whole tone. That is different from chromatic transposition, which preserves every semitone distance and would give D–E–F#. Both are legitimate operations, and confusing them produces notes you did not intend.',
          'Compare each variation with the original immediately. If the connection has disappeared, you changed more than one thing; keep the first two notes or the original rhythm and try again.',
        ),
        example('ex-m06-l02-d', 'Variation three: a diatonic sequence one step higher. Listen to how the last step shrinks to a semitone.'),
        exercise('q-m06-l02'),
        pianoTask(
          [
            'Play the original idea twice.',
            'Make a rhythmic variation and play original-then-variation as a pair.',
            'Make an ending variation and pair it the same way.',
            'Play the diatonic sequence one step higher and check the last interval by ear.',
          ],
          'If the whole phrase changes, preserve its first two notes or its rhythm deliberately.',
          'Make a fourth variation that changes register instead of pitch content.',
        ),
        reflection('Which variation kept the clearest connection to the original?'),
      ],
      makeItYours: 'Take a motif of your own from the last lesson and make the same three variations on it. Save the one you like best in the notebook.',
      ifDifficult: [
        'If the whole phrase changes, preserve its first two notes or its rhythm.',
        'Play original and variation back to back every time, never in isolation.',
        'Remember a diatonic sequence adjusts its intervals to the key; chromatic transposition does not.',
      ],
      readinessCheck: 'Can you create three variants while retaining an identifiable connection to the original?',
      takeaway: 'Change one thing; keep the rest so the listener can follow.',
      reviewTask: 'Make one rhythmic and one ending variation of a short motif.',
      reviewExerciseId: 'q-m06-l02',
    },
    {
      id: 'm06-l03',
      title: 'Aim for a note at a chord change',
      objective: 'Land intentionally on planned target notes at three of four chord changes, and repeat the resulting line.',
      beforeYouStart: 'Follows m06-l02. C major over C–Am–F–G, one chord per bar, slow enough that each change feels unhurried.',
      skills: ['improvisation', 'harmonization'],
      glossary: ['target-tone', 'non-chord-tone'],
      blocks: [
        prose(
          undefined,
          'Improvising becomes far easier when you know where you are going. Choosing a target note for each chord change turns four bars of open choice into four short journeys.',
        ),
        example('ex-m06-l03-a', 'Target notes E–E–A–G on the downbeat of each bar over C–Am–F–G.'),
        prose(
          'Understand',
          'Each target is a chord tone of the chord arriving at that moment: E in C, E in Am, A in F, G in G. Strong-beat chord tones are a scaffold — not because other notes are wrong, but because landing on them makes your line audibly deliberate.',
          'Sing a route between each pair of targets before you play. Start with one connecting note and leave rests; a line with space in it is easier to control and easier to hear.',
          'Later phrases can deliberately delay resolution or land on tension notes. That is a real and valuable choice. This lesson practises the opposite one, so that the choice exists at all.',
        ),
        exercise('q-m06-l03'),
        pianoTask(
          [
            'Play the four-bar loop slowly with bass roots only.',
            'Play only the four target notes on the downbeats, nothing else.',
            'Add one connecting note between targets, leaving rests.',
            'Repeat the line you just made, as closely as you can.',
          ],
          'If the next chord arrives too soon, use two bars per chord.',
          'Choose a different set of targets and play the loop again with them.',
        ),
        reflection('How many of the four targets did you actually reach on the downbeat? Count honestly.'),
      ],
      makeItYours: 'Pick a new set of four targets over the same loop — perhaps a descending line — and improvise towards them.',
      ifDifficult: [
        'If the next chord arrives too soon, use two bars per chord.',
        'Play only the targets for several loops before adding anything between them.',
        'Slow the tempo until nothing feels rushed.',
      ],
      readinessCheck: 'Can you land intentionally on three of four targets in a slow loop, assessed by yourself, and repeat the line?',
      takeaway: 'Know where you are going before you decide how to get there.',
      reviewTask: 'Play one four-bar loop landing on chosen targets at each change.',
      reviewExerciseId: 'q-m06-l03',
    },
    {
      id: 'm06-l04',
      title: 'Ask and answer',
      objective: 'Play an eight-bar invention whose second half is a recognisable answer to its first half.',
      beforeYouStart: 'Follows m06-l03. C major, 4/4. Use First Light’s harmony or simply C–G–C–C. A note-perfect transcription is not required to complete this lesson.',
      skills: ['improvisation', 'phrase-memory'],
      glossary: ['phrase', 'motif', 'cadence'],
      blocks: [
        prose(
          undefined,
          'You have heard question-and-answer phrases in Module 3. Now you will write one. The structure is simple: four bars that end open, four bars that close.',
        ),
        example('ex-m06-l04-a', 'A demonstration: a four-bar question ending over G, then a four-bar answer ending over C.'),
        prose(
          'Understand',
          'Reuse one motif across both halves. The answer should begin recognisably like the question and diverge only at the end. That reuse is what makes eight bars feel like one thought rather than two unrelated fragments.',
          'The question ends over G harmony, which leaves it open. The answer ends over C, which closes it. Those are the same two sensations you identified in Module 2 and Module 4, now being used as a compositional tool rather than a listening test.',
          'If eight bars is too much to hold, shrink the whole structure: a one-bar question and a one-bar answer teaches exactly the same thing. Length is not the skill here.',
        ),
        exercise('q-m06-l04'),
        pianoTask(
          [
            'Choose a harmony: C–G–C–C or First Light’s chart.',
            'Improvise a four-bar question that ends over G.',
            'Improvise a four-bar answer that reuses your opening and ends over C.',
            'Play all eight bars twice, keeping the relationship audible.',
          ],
          'If eight bars is too much, use a one-bar question and a one-bar answer.',
          'Make a second answer with a different ending and choose between them.',
        ),
        reflection('What exactly did your answer reuse from your question — rhythm, opening notes, contour, or all three?'),
      ],
      makeItYours: 'Save the phrase in the notebook, either as notes or as a written description. A description such as "rising four notes, rest, falling answer to C" is a complete record for this lesson.',
      ifDifficult: [
        'If eight bars is too much, use a one-bar question and a one-bar answer.',
        'Keep the answer’s first two notes identical to the question’s.',
        'Record a verbal description rather than notation if writing notes slows you down.',
      ],
      readinessCheck: 'Can you repeat an eight-bar invention with a recognisably related answer, even if individual notes vary slightly?',
      takeaway: 'An answer is the question with a different ending.',
      reviewTask: 'Improvise a one-bar question and a one-bar answer.',
      reviewExerciseId: 'q-m06-l04',
    },
  ],
);
