import { example, exercise, makeModule, pianoTask, prose, reflection } from './builder';

export const module12 = makeModule(
  'm12',
  12,
  'Independent playing and continued growth',
  'Recover a new melody, harmonize it without a chart, make a complete miniature, and choose what to practise next.',
  [
    {
      id: 'm12-l01',
      title: 'Recover a fresh melody',
      objective: 'Recover most of a new four-bar phrase by ear and explicitly locate any uncertainty.',
      beforeYouStart: 'Follows Module 11. A new four-bar phrase in C or G major, 60 BPM, generated within the course’s own limits. No notation appears until you request it.',
      skills: ['pitch-mapping', 'phrase-memory', 'inner-hearing'],
      glossary: ['contour', 'phrase'],
      blocks: [
        prose(
          undefined,
          'Everything in Modules 1 to 3 was preparation for this: hearing a melody you have never heard before and finding it.',
        ),
        example('ex-m12-l01-a', 'A fresh four-bar phrase in C major. Listen twice before touching the piano.', true),
        prose(
          'Understand',
          'Use the whole sequence you have been building. Listen. Sing. Chunk it into two-bar pieces. Find the pitches. Join the chunks. Do not open the notation until you have made a serious attempt.',
          'The phrase follows the course\'s own constraints: one key, mostly stepwise movement, no leap larger than a fifth, at most one eighth-note pair per bar, and an ending on the tonic. Knowing those constraints is legitimate help — they narrow the search considerably.',
          'The real target of this lesson is not a perfect recovery. It is an accurate self-diagnosis. Recovering three bars and knowing exactly which bar defeated you is a better result than recovering four and not knowing why.',
          'Each phrase has a stored seed, so you can return to this exact phrase later, and a different seed is available when you want a fresh attempt.',
        ),
        example('ex-m12-l01-b', 'A second fresh phrase, this time in G major. Use it as a later transfer attempt.', true),
        exercise('q-m12-l01'),
        pianoTask(
          [
            'Listen to the phrase twice with the notes hidden.',
            'Sing it, then chunk it into two-bar pieces.',
            'Find each chunk at the piano, then join them.',
            'Say out loud exactly where you were uncertain.',
          ],
          'If four bars is too much, work with two and return to the rest later.',
          'Recover the G major phrase as well, after the C one.',
        ),
        reflection('Which bar was uncertain, and what was uncertain about it — a pitch, an interval, or the rhythm?'),
      ],
      makeItYours: 'Save the phrase you recovered, along with a note about the uncertain spot. You will use this melody in the next lesson.',
      ifDifficult: [
        'If four bars is too much, use two and repeat later.',
        'A correct self-diagnosis is the point; partial recovery with clear diagnosis is a good result.',
        'Store the seed so you can revisit the same phrase later.',
      ],
      readinessCheck: 'Can you recover most of the phrase and explicitly locate any uncertainty?',
      takeaway: 'Knowing precisely what you could not hear is itself a skill.',
      reviewTask: 'Recover two bars of a phrase you have not heard before.',
      reviewExerciseId: 'q-m12-l01',
    },
    {
      id: 'm12-l02',
      title: 'Harmonize without a supplied chart',
      objective: 'Sustain four bars with a deliberate ending and explain one chord choice.',
      beforeYouStart: 'Follows m12-l01. Use the melody you recovered, or First Light with its chords hidden. C or G major, any comfortable tempo.',
      skills: ['harmonization', 'accompaniment'],
      glossary: ['harmonic-rhythm', 'cadence', 'lead-sheet'],
      blocks: [
        prose(
          undefined,
          'No chart this time. You have the eight-step checklist from Module 3, and everything you have heard since.',
        ),
        prose(
          'The checklist',
          'Sing the whole phrase and find a plausible home note, then check it with a closing gesture. Find the melody and rhythm in small groups. Mark phrase endings, long notes and strong beats, and start with one chord per bar or per two bars. Try I and V first, then IV and vi.',
          'Inspect sustained melody notes against chord tones and treat short connecting notes flexibly. Play bass roots only while singing the melody. Add compact chords, then one accompaniment pattern. Finally compare at least two plausible choices and record why one suits the phrase.',
        ),
        example('ex-m12-l01-a', 'The melody with no chord symbols. Apply the checklist to it.', true),
        prose(
          'Understand',
          'If finding the pitches and choosing the chords at the same time overloads your attention, do them separately. Confirm the melody completely first, then start on harmony with the melody secure.',
          'The app has a reference solution, and it is a worked example rather than the only acceptable answer. Two different harmonizations of the same melody can both be good, as you heard in Modules 4 and 9.',
          'Record your manual readiness separately from any multiple-choice result. They measure different things, and combining them would tell you less than either does alone.',
        ),
        exercise('q-m12-l02'),
        pianoTask(
          [
            'Confirm the melody by ear before touching the harmony.',
            'Work through the eight-step checklist in order.',
            'Compare two candidate progressions at the same tempo.',
            'Play four bars with an accompaniment and a deliberate ending.',
          ],
          'If finding pitches and choosing chords together overloads you, confirm the melody first and harmonize afterwards.',
          'Harmonize the second generated phrase in G as well.',
        ),
        reflection('Which chord choice took the longest to settle, and what finally decided it?'),
      ],
      makeItYours: 'Save your progression with a written reason in the Harmony Lab, alongside the alternative you rejected.',
      ifDifficult: [
        'If pitches and chords together overload attention, confirm the melody first.',
        'Start with one chord per two bars and add changes only where needed.',
        'Record manual readiness separately from any quiz result.',
      ],
      readinessCheck: 'Can you sustain four bars with a deliberate ending and explain one chord choice?',
      takeaway: 'The checklist works on melodies nobody has harmonized for you.',
      reviewTask: 'Harmonize two bars of an unfamiliar melody and say why.',
      reviewExerciseId: 'q-m12-l02',
    },
    {
      id: 'm12-l03',
      title: 'Make a complete miniature',
      objective: 'Play a short original piece with a beginning, related phrases and an intentional ending.',
      beforeYouStart: 'Follows m12-l02. One key, one familiar accompaniment pattern, one chord per bar. Thirty to ninety seconds is a suggestion; shorter and coherent is better than longer and vague.',
      skills: ['improvisation', 'arranging', 'accompaniment'],
      glossary: ['phrase', 'motif', 'cadence'],
      blocks: [
        prose(
          undefined,
          'A miniature is a complete piece rather than an exercise. It needs only five parts: a short introduction, a question, an answer, one variation, and an ending.',
        ),
        example('ex-m12-l03-a', 'A demonstration miniature with all five sections. Notice how little material it uses.'),
        prose(
          'Understand',
          'Use one key and one accompaniment pattern. Changing either partway through is a decision you can make later; for now, consistency is what makes the piece hold together.',
          'Reuse material deliberately. The answer should recall the question, and the variation should recall both. If you find yourself inventing new material every bar, the piece will feel restless — and it will also be much harder to play.',
          'The introduction can be as small as two bars of the accompaniment pattern alone, and the ending as small as one long tonic note. Neither needs to be clever.',
          'If the piece grows unmanageable, use two bars per section and one chord per bar. Ten bars of music you can actually play is a complete miniature.',
        ),
        exercise('q-m12-l03'),
        pianoTask(
          [
            'Choose a key, a pattern, and a chord per bar.',
            'Play a two-bar introduction of accompaniment alone.',
            'Play your question, then an answer that recalls it.',
            'Add one variation, then an intentional ending.',
            'Play the whole thing through twice.',
          ],
          'If it grows unmanageable, use two bars per section and one chord per bar.',
          'Play the miniature in a second key.',
        ),
        reflection('Which section was hardest to make, and did you solve it by adding material or by removing some?'),
      ],
      makeItYours: 'Save the melody notes or a practice-journal entry, plus an arrangement recipe: key, chords, pattern, tempo. That recipe is enough to rebuild the piece in a month.',
      ifDifficult: [
        'If it grows unmanageable, use two bars per section and one chord per bar.',
        'Reuse material rather than inventing new material every bar.',
        'A shorter coherent result is a complete result.',
      ],
      readinessCheck: 'Can you play a beginning, related phrases and an intentional ending without inventing new material every bar?',
      takeaway: 'A complete small piece teaches more than an endless unfinished one.',
      reviewTask: 'Play a two-bar introduction and an intentional ending.',
      reviewExerciseId: 'q-m12-l03',
    },
    {
      id: 'm12-l04',
      title: 'Transfer and make a personal plan',
      objective: 'State what you can now do, what still needs help, and choose three specific next practice tasks.',
      beforeYouStart: 'Follows m12-l03. Any key. Have your earlier notebook entries open — especially your reflection from m01-l01.',
      skills: ['transposition', 'inner-hearing', 'improvisation'],
      glossary: ['transposition', 'audiation'],
      blocks: [
        prose(
          undefined,
          'The last lesson is a comparison and a plan. It does not certify anything, and it does not produce a score.',
        ),
        example('ex-m01-l01-a', 'Replay the very first phrase of the course: C–D–C. Compare how it feels now with what you wrote in Module 1.', true),
        prose(
          'Understand',
          'Do three things in order. Replay an early ear task and notice what has changed. Harmonize a familiar phrase, using the checklist from memory this time. Then move that phrase to another key.',
          'Compare the result with your own earlier notes. The app will not invent improvement statistics for you — no percentages, no charts claiming your ear improved by some amount. Your own written observations from Modules 1, 3 and 8 are the honest record.',
          'Then choose one continuing focus: hearing longer phrases, new keys, steadier accompaniment, richer harmony, or another instrument. One focus, not five.',
          'From that focus, pick three specific practice tasks. The continued-practice ladder offers: recover one new two-bar melody; harmonize a familiar phrase two ways; play one phrase in two keys; improvise an answer to a motif; simplify a favourite piece to melody and bass; revisit a difficult transition slowly.',
          'Finishing this course does not certify unrestricted improvisation or mastery of any other instrument. It means you have a working method, and the method is what continues.',
        ),
        exercise('q-m12-l04'),
        pianoTask(
          [
            'Replay an early ear task and write one sentence comparing it with your first attempt.',
            'Harmonize a familiar phrase from memory using the checklist.',
            'Move that phrase to another key.',
            'Choose one continuing focus and three specific next tasks.',
          ],
          'If comparing with old notes is discouraging, compare only the method you used, not the result.',
          'Transfer one phrase to another instrument, remembering its fingering must be learned separately.',
        ),
        reflection('Write three sentences: what you can now do, what still needs help, and what you will practise next.'),
      ],
      makeItYours: 'Save your three chosen tasks in the notebook. The Progress page will offer them to you as recommendations from now on.',
      ifDifficult: [
        'Compare with your own earlier notes, not with anyone else’s standard.',
        'Choose one continuing focus rather than several.',
        'If a task feels vague, make it smaller and more specific.',
      ],
      readinessCheck: 'Can you state what you can now do, what still needs help, and select three specific next practice tasks?',
      takeaway: 'The method continues after the course ends; that is what you were building.',
      reviewTask: 'Replay one early task and compare it with your earliest note.',
      reviewExerciseId: 'q-m12-l04',
    },
  ],
);
