import { example, exercise, makeModule, pianoTask, prose, reflection } from './builder';

export const module05 = makeModule(
  'm05',
  5,
  'Make accompaniment comfortable',
  'Reduce hand travel, choose a repeatable left-hand pattern, and keep the melody audible above it.',
  [
    {
      id: 'm05-l01',
      title: 'Inversions reduce travel',
      objective: 'Play a four-chord sequence with compact voicings and name each chord’s root and lowest note separately.',
      beforeYouStart: 'Follows Module 4. C major, 60 BPM, left hand between C3 and A3. Two-note voicings or bass alone are acceptable substitutes.',
      skills: ['accompaniment', 'coordination'],
      glossary: ['inversion', 'root-and-bass', 'voicing'],
      blocks: [
        prose(
          undefined,
          'Playing every chord in root position means jumping around the keyboard. Inversions let the same chords sit close together, which makes accompaniment far easier to sustain while your attention is on the melody.',
        ),
        example('ex-m05-l01-a', 'C–F–G–C using compact voicings: C3–E3–G3, C3–F3–A3, B2–D3–G3, C3–E3–G3. Notice how little the hand moves.'),
        prose(
          'Understand',
          'Root position, first inversion and second inversion put the root, third and fifth in the bass respectively. The chord identity never changes. C–E–G, E–G–C and G–C–E are all C major.',
          'Name two things separately for every chord you play: its root, which gives it its name, and its lowest sounding note. In the sequence above, the second chord is F major with C in the bass, written F/C. It is not a C chord.',
          'Keeping shared notes or moving to the nearest voice is a useful arranging habit. It is not a rule that replaces listening, and some styles deliberately leap. Use it because it makes your hand comfortable, not because it is obligatory.',
        ),
        exercise('q-m05-l01'),
        pianoTask(
          [
            'Play the compact sequence four times slowly, watching how far your hand travels.',
            'For each chord, say its root and its lowest note out loud.',
            'Identify F/C correctly without checking the screen.',
          ],
          'If three-note shapes feel awkward, use two notes or the bass note alone.',
          'Find a second compact route through the same four chords and compare the two.',
        ),
        reflection('How far does your left hand move across the whole sequence now, compared with root positions?'),
      ],
      makeItYours: 'Take C–Am–F–G and find a compact route through it where no voice moves more than a few semitones. Play it four times.',
      ifDifficult: [
        'If three-note shapes feel awkward, use two notes or bass alone.',
        'Play the sequence as slow whole notes with no pulse at all until the shapes are automatic.',
        'Say "root" and "bass" separately for each chord, every time.',
      ],
      readinessCheck: 'Can you move through the compact sequence four times slowly and identify F/C correctly?',
      takeaway: 'The chord is named by its root; the bass is just its lowest note.',
      reviewTask: 'Play one four-chord sequence with compact voicings.',
      reviewExerciseId: 'q-m05-l01',
    },
    {
      id: 'm05-l02',
      title: 'Bass and chord patterns',
      objective: 'Hold one left-hand pattern for four bars without stopping at the chord changes.',
      beforeYouStart: 'Follows m05-l01. Small Steps (S02) bars 1–4, C major, 4/4, at 50–60 BPM — slower than the study’s own tempo on purpose.',
      skills: ['accompaniment', 'rhythm', 'coordination'],
      glossary: ['texture', 'voicing'],
      blocks: [
        prose(
          undefined,
          'Two patterns cover a great deal of music. The block pattern plays the full compact chord on beats 1 and 3. The bass-and-chord pattern plays the bass root on beats 1 and 3 with the chord on beats 2 and 4.',
        ),
        example('ex-m05-l02-b', 'C–Am–F–G with a bass-and-chord pattern. Listen to the alternation before you play it.'),
        prose(
          'Understand',
          'Start without any melody. Play C–Am–F–G with the block pattern for four bars, then with the bass-and-chord pattern for four bars. Your only goal is that the pulse does not hesitate when the chord changes.',
          'Most people lose the pulse exactly at the bar line, because the hand is looking for the next shape. Practise just that transition: play the last beat of one bar and the first beat of the next, repeatedly, until it is boring.',
          'Then add the melody of Small Steps bars 1–4. Sing the melody first while your left hand keeps the pattern, and only add the right hand when the left can continue without your attention.',
          'You may simplify the left hand to a single bass note on beat 1. Consistency is more useful here than density.',
        ),
        example('ex-m05-l02-a', 'Small Steps bars 1–4. Sing this melody over your pattern before you play it.'),
        exercise('q-m05-l02'),
        pianoTask(
          [
            'Play the block pattern on C–Am–F–G for four bars at 50 BPM.',
            'Switch to bass-and-chord and play four more bars.',
            'Keep one pattern going for four bars while singing the melody.',
            'Add the right hand only if it stays comfortable.',
          ],
          'If the pulse stops at chord changes, practise only the transition across the bar line.',
          'Play all eight bars of Small Steps with one consistent pattern.',
        ),
        reflection('Which pattern let you keep the steadier pulse? Use that one for the next few days.'),
      ],
      makeItYours: 'Choose the pattern you find easiest and play your own four-bar chord loop with it, singing anything you like on top.',
      ifDifficult: [
        'If the pulse stops at chord changes, practise just the transition across the bar line.',
        'Simplify the left hand to a bass note on beat 1.',
        'Drop the tempo to 45 BPM; the pattern matters more than the speed.',
      ],
      readinessCheck: 'Can you keep one pattern for four bars while singing the melody, then add the right hand if comfortable?',
      takeaway: 'A steady simple pattern beats a rich pattern that stops at every bar line.',
      reviewTask: 'Play four bars of one accompaniment pattern without hesitating at a change.',
      reviewExerciseId: 'q-m05-l02',
    },
    {
      id: 'm05-l03',
      title: 'Flowing broken chords',
      objective: 'Play a broken-chord pattern through four bars, changing to the correct harmony at each bar line.',
      beforeYouStart: 'Follows m05-l02. C major, 4/4, 60 BPM. Chords C, Am, F and G. No pedal is required in this lesson.',
      skills: ['accompaniment', 'coordination'],
      glossary: ['arpeggio', 'voicing'],
      blocks: [
        prose(
          undefined,
          'Broken chords sound the chord tones one after another instead of together. They give a flowing texture from exactly the same harmony you already know.',
        ),
        example('ex-m05-l03-a', 'First Light bars 1–4. Try this with the compact broken pattern first, then with the open one.'),
        prose(
          'Understand',
          'The compact broken pattern plays voicing tones 1–2–3–2, one per beat, inside a small hand position. The open broken pattern plays root, fifth, upper root, fifth, which sounds wider and needs more reach.',
          'One distinction matters here. Chord-tone index is not the same as scale degree. In the compact pattern on F major, tone 1 is F, tone 2 is A and tone 3 is C — those are the chord\'s own notes, not degrees 1, 2 and 3 of the key.',
          'If the open pattern stretches your hand, move between the notes rather than holding them, or choose the compact pattern instead. Do not hold a large interval physically to make a pattern work. Aim for an even, quiet tone before you aim for speed.',
        ),
        exercise('q-m05-l03'),
        pianoTask(
          [
            'Play the compact broken pattern on C, then Am, then F, then G, one bar each.',
            'Repeat with the open broken pattern if it is comfortable.',
            'Apply one pattern to First Light bars 1–4, changing harmony exactly at each bar line.',
          ],
          'If the open pattern stretches the hand, move between notes or use the compact pattern.',
          'Play all eight bars of First Light with a broken pattern and a singing melody.',
        ),
        reflection('Did the harmony change land exactly on the bar line, or slightly late?'),
      ],
      makeItYours: 'Choose one broken pattern and play a four-bar loop of your own chords with it, keeping the tone even and quiet throughout.',
      ifDifficult: [
        'If the open pattern stretches the hand, move between notes or choose the compact pattern.',
        'Never hold a large interval physically to make the pattern work.',
        'Practise the harmony change alone: last beat of one bar, first beat of the next.',
      ],
      readinessCheck: 'Can you play four bars with the correct new harmony at each bar line, without pedal?',
      takeaway: 'Broken chords are the same harmony spread across time.',
      reviewTask: 'Play one broken-chord pattern through two chord changes.',
      reviewExerciseId: 'q-m05-l03',
    },
    {
      id: 'm05-l04',
      title: 'Balance, coordination, and pedal',
      objective: 'Play four bars with a clearly audible melody and hear the difference between clear and blurred harmony.',
      beforeYouStart: 'Follows m05-l03. First Light, C major, 4/4, 60 BPM. Pedal is optional and comes last. The app cannot assess your touch or your pedalling acoustically.',
      skills: ['coordination', 'accompaniment'],
      glossary: ['texture', 'voicing'],
      blocks: [
        prose(
          undefined,
          'Balance is the difference between an accompaniment that supports a melody and one that buries it. It is a listening task before it is a technical one.',
        ),
        example('ex-m05-l04-a', 'First Light bars 1–4. In the app’s mix the melody is deliberately louder than the accompaniment — copy that balance at your piano.'),
        prose(
          'Understand',
          'Build the texture in three stages. First, hands separately: melody alone until it is fluent, accompaniment alone until it is even. Second, melody with one bass note per bar — a very thin texture that is easy to balance. Third, melody with your chosen pattern.',
          'Make the melody perceptibly stronger. Most players naturally play the busier hand louder, so you will probably have to make the left hand quieter on purpose rather than making the right hand louder.',
          'Only once the notes are clear, try the pedal. The usual order at a chord change is: play the new harmony, lift the old pedal, then depress again. If that sequence blurs the phrase, practise without pedal; nothing in this course requires it.',
        ),
        exercise('q-m05-l04'),
        pianoTask(
          [
            'Play four bars hands separately until both are fluent.',
            'Play the melody with one bass note per bar and listen for balance.',
            'Add your chosen pattern, keeping the left hand quieter.',
            'Optionally add pedal, changing after each harmony change, and compare with no pedal.',
          ],
          'If coordination fails, remove inner accompaniment notes and keep the bass alone.',
          'Play all eight bars with balance and pedal, then record a note about which bars blurred.',
        ),
        reflection('Which was harder: the coordination, or hearing the balance while you played?'),
      ],
      makeItYours: 'Play the same four bars twice — once with pedal, once without — and write one sentence about which you prefer for this phrase.',
      ifDifficult: [
        'If coordination fails, remove inner accompaniment notes.',
        'If pedal blurs the phrase, practise without it. It is optional throughout this course.',
        'Play the accompaniment at a whisper and see whether the melody still feels too quiet.',
      ],
      readinessCheck: 'Can you complete four bars with an audible melody and distinguish clear from blurred harmony by listening?',
      takeaway: 'Make the accompaniment quieter rather than the melody louder.',
      reviewTask: 'Play two bars with melody and bass, listening only for balance.',
      reviewExerciseId: 'q-m05-l04',
    },
  ],
);
