import { example, exercise, makeModule, pianoTask, prose, reflection } from './builder';

export const module04 = makeModule(
  'm04',
  4,
  'Hear and choose basic chords',
  'Tell major from minor, hear departure and return, and choose a chord that supports a melody.',
  [
    {
      id: 'm04-l01',
      title: 'Major and minor chord colour',
      objective: 'Identify a triad as major or minor by ear and name the note that changes between them.',
      beforeYouStart: 'Follows Module 3. C major reference, 60 BPM. Both qualities are played in the same register with the same rhythm so nothing but the third gives the answer away.',
      skills: ['chord-hearing'],
      glossary: ['triad', 'semitone'],
      blocks: [
        prose(
          undefined,
          'A triad has three notes: a root, a third and a fifth. Change the third by one semitone and the whole chord changes quality. That single note is what you are learning to hear.',
        ),
        example('ex-m04-l01-a', 'C–E–G, then C–Eb–G. Same root, same fifth, same register, same rhythm. Only the middle note moved.'),
        prose(
          'Understand',
          'Major triads are 0–4–7 semitones above the root; minor triads are 0–3–7. In C, that is C–E–G against C–Eb–G.',
          'You will often see major described as happy and minor as sad. Treat that as a loose association rather than a fact. Plenty of cheerful music is in minor and plenty of sad music is in major; what you can rely on is the sound of the interval, not the emotion attached to it.',
          'Keep the register constant while you are learning. If one chord is played high and bright and the other low and dark, you may be hearing register rather than quality. The exercises below deliberately hold everything else steady.',
        ),
        example('ex-m04-l01-b', 'Four contrasting pairs with different roots. Identify the quality of each, then check.', true),
        exercise('q-m04-l01'),
        pianoTask(
          [
            'Play C–E–G, then lower E to Eb and play it again. Repeat until the change is obvious.',
            'Turn A minor into A major by raising C to C#.',
            'Identify six triads with randomised roots, listening once each.',
          ],
          'If recognition depends on register, compare both qualities on the same root before you start changing roots.',
          'Add the diminished triad C–Eb–Gb and compare all three qualities on one root.',
        ),
        reflection('Can you hear the third as a separate note inside the chord yet, or only the chord as a whole?'),
      ],
      makeItYours: 'Take a two-bar phrase you have played before and accompany it once with a major chord and once with the parallel minor. Say which you prefer for that phrase and why.',
      ifDifficult: [
        'If recognition depends on register, compare both qualities on the same root before changing roots.',
        'Play the two chords slowly one after the other, then only the two thirds.',
        'Sing the third of each chord out of the texture.',
      ],
      readinessCheck: 'Can you identify four of six triads and name the note that changes between C major and C minor?',
      takeaway: 'The third decides the quality; everything else can stay the same.',
      reviewTask: 'Identify the quality of one triad played in a neutral register.',
      reviewExerciseId: 'q-m04-l01',
    },
    {
      id: 'm04-l02',
      title: 'I and V: departure and return',
      objective: 'Hear a phrase leave on V and choose the chord that returns it home.',
      beforeYouStart: 'Follows m04-l01. C major, 60 BPM. Left hand may play single bass roots instead of full chords.',
      skills: ['chord-hearing', 'harmonization', 'tonal-center'],
      glossary: ['roman-numeral', 'cadence', 'tonic-predominant-dominant'],
      blocks: [
        prose(
          undefined,
          'Two chords are enough to make a small piece of music work. I is home. V leaves home in a way that points back.',
        ),
        example('ex-m04-l02-b', 'C–G–C as block chords. Then listen again imagining only the bass roots: C, G, C.'),
        prose(
          'Understand',
          'In C major, I is C–E–G and V is G–B–D. Roman numerals describe the root of the chord relative to the key, not the lowest note currently sounding — that distinction becomes important in Module 5.',
          'Now hear a melody over them. The example below plays G–B–D over G harmony, then E–D–C over C. Notice how the melody and the harmony arrive together: the tune reaches C at the same moment the chord does.',
          'Compare that with stopping on the G harmony instead. The phrase is not wrong, it is simply open — it sounds like a question. That is the same open ending you met in Module 2, now with a chord underneath it.',
          'A caution about names: V–I is a strong return, but not every V–I deserves a specific classical cadence label. Those labels also depend on voicing and on where the melody lands. "It returns home" is the useful description at this stage.',
        ),
        example('ex-m04-l02-a', 'A melody over G, then over C. Where does it arrive?'),
        exercise('q-m04-l02'),
        pianoTask(
          [
            'Play C–G–C slowly while keeping a steady pulse, using bass roots if chords are awkward.',
            'Choose the closing chord by ear in three contextual trials.',
            'Play the melody with your right hand and the two bass roots with your left.',
          ],
          'If hand movement is distracting, play only C3–G2–C3 in the left hand — three single notes.',
          'Add a IV chord before the final I and compare C–G–C with C–G–F–C.',
        ),
        reflection('Did you hear the return before you found the chord, or did finding the chord teach you the sound?'),
      ],
      makeItYours: 'Improvise a four-beat phrase over G that ends unresolved, then a four-beat phrase over C that closes. Play them as a pair, twice.',
      ifDifficult: [
        'If hand movement is distracting, play C3–G2–C3 only.',
        'Do not require fast root-position jumps; single bass notes are enough.',
        'Sing the melody while your left hand plays the two roots.',
      ],
      readinessCheck: 'Can you choose a closing I after hearing V in three contextual trials, and play C–G–C while keeping a pulse?',
      takeaway: 'V points home; I arrives. Melody and harmony can arrive together.',
      reviewTask: 'Hear one phrase ending on V and choose the chord that closes it.',
      reviewExerciseId: 'q-m04-l02',
    },
    {
      id: 'm04-l03',
      title: 'Add IV and vi',
      objective: 'Name two plausible chords that contain a given melody note and hear how each one changes the phrase.',
      beforeYouStart: 'Follows m04-l02. C major, 60 BPM. Candidate chords are C, F, G and Am.',
      skills: ['chord-hearing', 'harmonization'],
      glossary: ['roman-numeral', 'tonic-predominant-dominant', 'triad'],
      blocks: [
        prose(
          undefined,
          'Two more chords open most of the course\'s repertoire. F is IV and A minor is vi. Both contain the note A, and that overlap is the point of this lesson.',
        ),
        example('ex-m04-l03-a', 'C–F–G–C. A familiar progression built from I, IV and V.'),
        example('ex-m04-l03-b', 'C–Am–F–G. The same key, a different route, a noticeably different mood.'),
        prose(
          'Understand',
          'F major is F–A–C. A minor is A–C–E. They share two notes — A and C — which is why either can support a melody sitting on A. That is your first experience of a genuine choice rather than a correct answer.',
          'Listen to the example below: A4–G4–E4 over F, then over Am, then over C. Over F and Am the sustained A is a chord tone. Over C it is not, and you hear a gentle tension — not a mistake, but a different effect that has to be intended.',
          'Choosing between plausible chords is not a calculation. It depends on the phrase around the bar, on what came before, and on what you want the passage to do. Listening to each candidate with the whole phrase is the only reliable method.',
        ),
        example('ex-m04-l03-c', 'The same three notes over F, then Am, then C. Listen to what the sustained A does in each case.'),
        exercise('q-m04-l03'),
        pianoTask(
          [
            'Play C–F–G–C slowly with bass roots, then with triads.',
            'Play C–Am–F–G the same way.',
            'Name two chords that contain A, then play the melody fragment over each.',
          ],
          'If there are too many labels at once, keep C, F and G first, and add Am only when those three are comfortable.',
          'Add Dm to the candidate set and find which melody notes it supports.',
        ),
        reflection('Over which chord did the sustained A sound most restful to you? There is no single right answer here.'),
      ],
      makeItYours: 'Choose one bar of a melody you know and harmonize it twice, once with IV and once with vi. Keep the version you prefer and say why in one sentence.',
      ifDifficult: [
        'If there are too many labels, keep C, F and G first and add Am afterwards.',
        'Play only the bass roots while you sing the melody.',
        'Compare just two candidates at a time, never three.',
      ],
      readinessCheck: 'Can you play both progressions slowly and name two candidate chords containing A?',
      takeaway: 'Several chords can support the same melody note; the phrase decides.',
      reviewTask: 'Name two chords containing a given melody note and hear both.',
      reviewExerciseId: 'q-m04-l03',
    },
    {
      id: 'm04-l04',
      title: 'Harmonize a four-bar melody',
      objective: 'Choose one chord per bar for a four-bar melody and explain one choice using a long note or a phrase ending.',
      beforeYouStart: 'Follows m04-l03. First Light bars 5–8, C major, 4/4, 60 BPM. Candidate chords: C, F, G, Am. The reference solution is one answer, not the answer.',
      skills: ['harmonization', 'chord-hearing'],
      glossary: ['harmonic-rhythm', 'cadence', 'lead-sheet'],
      blocks: [
        prose(
          undefined,
          'Here is the reusable procedure you will use for the rest of the course, applied for the first time to a real four-bar phrase.',
          'Sing the phrase and find a plausible home note. Find the melody and rhythm in small groups. Mark phrase endings, long notes and strong beats. Try I and V first, then IV and vi. Check sustained melody notes against chord tones. Play bass roots only while you sing. Add compact chords, then one pattern. Finally, compare at least two plausible choices and record why one suits the phrase.',
        ),
        example('ex-m04-l04-a', 'Bars 5–8 with F–C–G–C. This is the reference solution.'),
        prose(
          'Understand',
          'Work through bar 5. The melody is A4–A4–G4. F major contains A, and so does A minor. The brief G at the end of the bar does not automatically demand a new chord — short connecting notes can pass over a held harmony.',
          'Continue into bar 6, E4–D4–C4, which sits comfortably over C. Then hear G under bar 7 and C under bar 8, and the phrase closes.',
          'Now the alternative. Am–C–G–C uses A minor in bar 5 instead of F. Both are defensible: F places A as its third and leans outward; Am places A as its root and stays closer to the tonic region. Neither is rejected simply for differing from the reference arrangement.',
        ),
        example('ex-m04-l04-b', 'The same four bars with Am–C–G–C. Compare it directly with the version above.'),
        exercise('q-m04-l04'),
        pianoTask(
          [
            'Play the four bars with bass roots only while singing the melody.',
            'Add compact triads once the roots feel secure.',
            'Play both progressions at the same tempo and choose one.',
            'Say out loud which long note or ending justified your choice.',
          ],
          'If it sounds busy, change chords only every two bars as an experiment, then compare with one chord per bar.',
          'Harmonize bars 1–4 as well and play all eight bars with your own chart.',
        ),
        reflection('Which single melody note did most of the work in your decision?'),
      ],
      makeItYours: 'Save your chosen progression in the Harmony Lab with one sentence explaining the choice. Add the alternative as a second arrangement so you can hear both later.',
      ifDifficult: [
        'If it sounds busy, change only every two bars as an experiment, then compare.',
        'Play bass roots alone until the harmonic shape is clear.',
        'Do not treat an alternative as wrong merely because it differs from the reference.',
      ],
      readinessCheck: 'Can you support the phrase with a chosen progression and explain one choice using a long note or an ending?',
      takeaway: 'Harmonizing is comparing plausible options, not finding the one hidden answer.',
      reviewTask: 'Harmonize one bar two ways and say which you prefer.',
      reviewExerciseId: 'q-m04-l04',
    },
  ],
);
