import { example, exercise, makeModule, pianoTask, prose, reflection } from './builder';

export const module01 = makeModule(
  'm01',
  1,
  'Connect the inner sound to a key',
  'Turn a sound you have just heard into an intention, and an intention into a key you press on purpose.',
  [
    {
      id: 'm01-l01',
      title: 'Hear a short phrase, then find it',
      objective: 'Reproduce a two- or three-note phrase on the piano after hearing it, and say whether a missed note was above or below what you intended.',
      beforeYouStart: 'No prior lesson needed. Sit at the piano with your device nearby and find middle C (C4). Examples are in C major at 60 beats per minute. You can already read notation; here the instruction comes from a sound instead.',
      skills: ['inner-hearing', 'pitch-mapping'],
      glossary: ['audiation', 'semitone'],
      blocks: [
        prose(
          undefined,
          'You will practise connecting a sound to a piano key. You can already use notation to tell your fingers where to go. Here, the instruction comes from a sound you have just heard. It is normal to need a few attempts.',
          'Keep the volume comfortable and leave the left hand free for now. Nothing in this lesson is timed, and nothing is measured except by you.',
        ),
        example('ex-m01-l01-a', 'Play the example once. It begins on C, moves to a nearby higher note, and comes back. Listen again without touching the piano. Can you imagine its final note after the sound stops?'),
        prose(
          'Understand',
          'You do not need to identify a note out of silence. The first C is your reference. What you are learning is how the next sound relates to it. Hearing whether a note repeats, rises, or falls already gives your hands useful information before you start searching.',
          'Hum the phrase in a comfortable octave. If humming is awkward, imagine it silently and listen again. The purpose is to hold the sound long enough to compare it with the piano, not to judge your singing voice. A supplied reference pitch is completely normal; nothing here requires you to remember concert pitch from memory.',
          'The phrase in the example is C4 for one beat, D4 for one beat, then C4 for two beats. In Learn mode those notes can stay on screen. In Try by ear mode the middle note stays hidden until you ask for a hint or reveal the answer.',
        ),
        prose(
          'Try it',
          'Play C, then find the higher note you heard, then return to C. Before each attempt, hear the phrase internally. If your chosen middle note sounds too high, try a lower nearby key. If it sounds too low, try a higher one. Compare the whole phrase after each adjustment, not just the one note.',
          'Repeat until you can play it twice in a row. Now listen to the second phrase below: C, a higher note, C. Its middle note is farther away. Try to find it before showing the answer.',
        ),
        example('ex-m01-l01-b', 'The second phrase. Its middle note is farther from C than the first one was. Find it before revealing.', true),
        exercise('q-m01-l01'),
        pianoTask(
          [
            'Alternate the two phrases three times, listening to the app before each one.',
            'Choose one phrase and play it after a quiet breath, with no replay during the breath.',
            'Give yourself time to correct it. Correcting is part of the exercise, not a failure.',
          ],
          'Use only C and D. Play each separately, sing or imagine it, and compare, until those two sounds feel clearly different.',
          'Try the same two phrases starting from G instead of C, keeping the same shape.',
        ),
        exercise('q-m01-l01-echo'),
        reflection('Which was easier: remembering the sound, or finding it on the keyboard? Write one sentence — it will be useful in Module 12.'),
      ],
      makeItYours: 'Sing a new three-note phrase using the notes you found. Play what you sang, then repeat that exact idea. If your fingers play something different, decide whether to correct the fingers or intentionally adopt the new phrase; notice that those are two different choices.',
      ifDifficult: [
        'Use only C and D. Play each separately, sing or imagine it, and compare. Return to the short phrase once those two sounds feel distinguishable.',
        'If remembering is harder than finding keys, shorten the pause before you play.',
        'If searching still feels random, reduce the whole exercise to two notes and stay there for a few days.',
      ],
      readinessCheck: 'Can you reproduce two of three short echoes, with corrections allowed, and say whether a missed note was above or below the sound you intended?',
      takeaway: 'Hear an intention, play, then compare. That loop is the whole course in miniature.',
      reviewTask: 'Revisit one phrase and find it before revealing its notes.',
      reviewExerciseId: 'q-m01-l01',
    },
    {
      id: 'm01-l02',
      title: 'Repeats, steps, and leaps',
      objective: 'Describe what a melody does between notes — same, up, or down — and tell a scale step apart from a larger skip.',
      beforeYouStart: 'Follows m01-l01. C major, 60 BPM, right hand only. You do not need interval names yet; hearing the shape comes first.',
      skills: ['pitch-mapping', 'inner-hearing'],
      glossary: ['contour', 'interval', 'semitone'],
      blocks: [
        prose(
          undefined,
          'First hear the shape. Naming the exact interval comes later, and naming it early tends to slow the hearing down.',
          'Two phrases follow. One moves by the smallest steps in the key; the other jumps between chord notes. Both start on C, so you have a reference each time.',
        ),
        example('ex-m01-l02-a', 'Phrase one. Say “same, up, down” out loud between each pair of notes.'),
        example('ex-m01-l02-b', 'Phrase two. Same rhythm, different distances. Which movements feel larger?'),
        prose(
          'Understand',
          'Between any two notes, only three things can happen: the sound repeats, it goes up, or it goes down. Get that reliable first and half the guesswork disappears.',
          'Then add one distinction: a step moves to the next note of the scale, and a skip jumps over at least one. In C major, C to D is a step and C to E is a skip. Be careful with one common assumption: not every scale step is the same physical distance. C to D is two semitones, but E to F is only one. Your ear learns the scale, not a fixed key spacing.',
          'When a leap confuses you, sing through the notes in between, then sing the leap again. Filling the gap once usually fixes the ear for the jump.',
        ),
        exercise('q-m01-l02'),
        exercise('q-m01-l02-shape'),
        pianoTask(
          [
            'Answer six contour prompts using the exercises above, listening once before each answer.',
            'Choose one of the two example phrases and find it on your piano.',
            'Play it twice with the same shape, at any speed that stays comfortable.',
          ],
          'Work with pairs of notes only. Play two notes, say “up” or “down”, then check.',
          'Play a phrase that mixes one step and one skip, and describe your own phrase in words afterwards.',
        ),
        reflection('Which direction is currently easier for you to hear, upward or downward movement?'),
      ],
      makeItYours: 'Invent a four-note phrase that uses exactly one skip and two steps. Play it, describe it in words, then play it again from your description rather than from memory of your fingers.',
      ifDifficult: [
        'If a leap is confusing, sing through the intermediate scale notes, then sing the leap again.',
        'If everything blurs, slow the playback and leave silence between the two notes.',
        'Do not assume every scale step is a whole tone. Compare C–D with E–F at the piano and listen to the difference.',
      ],
      readinessCheck: 'Can you answer five of six contour prompts after listening, and find one of the phrases on your piano?',
      takeaway: 'Direction first, distance second. The ear needs shape before it needs names.',
      reviewTask: 'Answer three contour prompts without looking at the keyboard.',
      reviewExerciseId: 'q-m01-l02',
    },
    {
      id: 'm01-l03',
      title: 'Remember a whole small phrase',
      objective: 'Hold a four- or five-note phrase through a pause and reproduce it as a whole, including its rhythm.',
      beforeYouStart: 'Follows m01-l02. C major, 60 BPM. Two bars in 4/4, with a rest at the end so the phrase has room to finish.',
      skills: ['phrase-memory', 'inner-hearing'],
      glossary: ['phrase', 'audiation'],
      blocks: [
        prose(
          undefined,
          'Replaying every single note can hide a weak phrase memory. If you listen, play one note, listen, play the next, your ear never has to hold anything. This lesson deliberately removes that crutch for a few seconds at a time.',
        ),
        example('ex-m01-l03-a', 'Listen twice. Sing the whole phrase. Wait one comfortable breath. Then play it.'),
        prose(
          'Understand',
          'The phrase is C–D–E–D, then C held for two beats and a two-beat rest. Five sounds and one silence. That is small enough to hold as a single object rather than as a list.',
          'The breath matters. During it, you cannot replay and you cannot check the keyboard. Whatever survives that pause is what your musical memory actually holds. If nothing survives, the phrase is too long for today — shorten it to three notes and come back.',
          'When you compare, compare whole phrases first. Play your version, play the original, and only then decide which single spot went wrong. Correcting the smallest trouble spot is the last step, not the first.',
        ),
        exercise('q-m01-l03'),
        example('ex-m01-l03-b', 'The same phrase with a different ending. Notice how little has to change for the phrase to feel different.'),
        pianoTask(
          [
            'Listen twice, sing, breathe once, then play the whole phrase.',
            'Repeat three times. If two of the three survive the breath, that is a good day.',
            'Now invent a different ending using only C, D and E, and play the phrase with your ending.',
          ],
          'Shorten the phrase to its first three notes and keep the breath.',
          'Delay for two breaths instead of one before playing.',
        ),
        reflection('Did the rhythm survive the pause as well as the pitches did? Which one faded first?'),
      ],
      makeItYours: 'Keep the first three notes of the phrase and invent a new ending using C, D and E only. Play your version twice so it becomes a decision rather than an accident.',
      ifDifficult: [
        'If the phrase disappears during the breath, shorten it to three notes.',
        'If it is easy, delay for two breaths.',
        'Remember the goal is musical memory, not visual memorization of the keyboard.',
      ],
      readinessCheck: 'Can you retain the phrase through the breath and reproduce its rhythm approximately?',
      takeaway: 'Hold the phrase as one shape, not as a list of separate notes.',
      reviewTask: 'Hear one phrase, wait a breath, and play it back.',
      reviewExerciseId: 'q-m01-l03',
    },
    {
      id: 'm01-l04',
      title: 'Your first accompanied invention',
      objective: 'Play a two-bar phrase of your own with a quiet held chord underneath, keeping both hands calm.',
      beforeYouStart: 'Follows m01-l03. C major, 60 BPM. Left hand plays a soft C3–E3–G3; right hand uses C4, E4 and G4 only. Slow is fine; quiet is better than loud.',
      skills: ['inner-hearing', 'coordination', 'improvisation'],
      glossary: ['triad', 'voicing'],
      blocks: [
        prose(
          undefined,
          'You have found sounds that you heard. Now you will make a sound of your own and support it. This is the first moment in the course where the two hands work together, so keep everything small.',
        ),
        example('ex-m01-l04-a', 'A two-bar phrase over one held C chord. Listen to how little the left hand does.'),
        prose(
          'Understand',
          'Sound a soft C3–E3–G3 in the left hand and let it ring. Then sing a two-bar phrase in the right hand using C4, E4 and G4. Those three notes are the chord you are already holding, which is why almost anything you sing will sit comfortably.',
          'That restriction is a starting exercise, not a rule. Melodies are not obliged to use only chord tones — you will add the notes in between from Module 2 onward. For today, the small set lets you concentrate on hearing your own idea and repeating it.',
          'Practise the hands separately first. Play the chord alone until it is even and quiet. Play the phrase alone until you can repeat it. Only then hold one chord under the whole phrase.',
        ),
        example('ex-m01-l04-b', 'A second phrase that ends on C4. Notice how ending on C makes the two bars feel finished.'),
        exercise('q-m01-l04'),
        pianoTask(
          [
            'Play C3–E3–G3 quietly and hold it while you count four slow beats.',
            'Sing a two-bar phrase using C4, E4 and G4, then find it in the right hand.',
            'Put them together: chord first, then the phrase over it. Repeat the same phrase twice.',
            'Make a second phrase that ends on C4 and play that one twice as well.',
          ],
          'Play only C3 in the left hand. One note is enough support for today.',
          'Change the left-hand chord to F3–A3–C4 for the second bar and adjust your phrase ending by ear.',
        ),
        reflection('Did having the chord underneath make your phrase easier or harder to hear? There is no right answer — note what actually happened.'),
      ],
      makeItYours: 'Invent a second phrase that ends on C4 rather than drifting to a stop. Play it twice, and say out loud what its ending does before you play it the second time.',
      ifDifficult: [
        'If coordination interrupts your hearing, use only C3 in the left hand.',
        'If the phrase keeps changing, sing it once more away from the keys before playing.',
        'Play the chord, lift your hand, then play the melody — you do not have to sustain both at first.',
      ],
      readinessCheck: 'Can you repeat one intended phrase with a quiet accompaniment underneath, even slowly?',
      takeaway: 'One held chord is enough accompaniment to turn a phrase into music.',
      reviewTask: 'Play one invented phrase over a held C chord and repeat it exactly.',
      reviewExerciseId: 'q-m01-l04',
    },
  ],
);
