import { example, exercise, makeModule, pianoTask, prose, reflection } from './builder';

export const module08 = makeModule(
  'm08',
  8,
  'Transfer the sound to new keys',
  'Carry a melody into another key by its degrees rather than by its finger pattern.',
  [
    {
      id: 'm08-l01',
      title: 'Think in degrees, not key shapes',
      objective: 'Play the same two bars in C major and in G major, naming the tonic of each before you start.',
      beforeYouStart: 'Follows Module 7. First Light bars 1–2, C major then G major, 60 BPM. Establish the new key before playing in it.',
      skills: ['transposition', 'tonal-center'],
      glossary: ['transposition', 'scale-degree'],
      blocks: [
        prose(
          undefined,
          'Transposition preserves musical relationships while changing the key. It is not moving your hand sideways on the white keys, and this lesson is where that distinction becomes concrete.',
        ),
        example('ex-m08-l01-a', 'First Light bars 1–2 in C major. Its degrees are 1–2–3–5 and 6–5–3.'),
        prose(
          'Understand',
          'Write the two bars as degrees: 1–2–3–5, then 6–5–3. Those degrees are the melody. C, D, E, G, A, G, E is just how they appear in one particular key.',
          'Establish G as home before you play anything — a quick G–C–D–G will do. Then play the same degrees: G, A, B, D, E, D, B.',
          'If you find yourself copying the white-key distances from the C version, stop and sing the complete G major scale once. G major contains F#, and although these two bars do not happen to use degree 7, knowing where the key\'s semitones fall is what stops the copying habit.',
          'As the key changes become comfortable, hide the note labels and keep the degrees visible. The degrees are the part that transfers.',
        ),
        exercise('q-m08-l01'),
        pianoTask(
          [
            'Play bars 1–2 in C and say the degrees out loud.',
            'Establish G major with G–C–D–G.',
            'Play the same degrees in G and name the starting tonic.',
            'Switch between the two keys three times without checking the screen.',
          ],
          'If you copy white-key distances, sing the complete G major scale once, including F#.',
          'Move the same two bars to F major as well.',
        ),
        reflection('Did you think in degrees or in letters when you played the G version?'),
      ],
      makeItYours: 'Take any two-bar phrase you already play and write it out as degrees. Then play it in a key you have not used for it before.',
      ifDifficult: [
        'If you copy white-key distances, sing the complete G major scale once.',
        'Do not force F# into a phrase that has no degree 7 — just know where it lives.',
        'Gradually hide note labels while keeping degrees visible.',
      ],
      readinessCheck: 'Can you play the two bars in both keys and name the starting tonic of each?',
      takeaway: 'Degrees travel between keys; finger patterns do not.',
      reviewTask: 'Play one two-bar phrase in C and then in G from its degrees.',
      reviewExerciseId: 'q-m08-l01',
    },
    {
      id: 'm08-l02',
      title: 'F major and D major',
      objective: 'Play a final resolution in F major or D major with correct spelling and without returning to C.',
      beforeYouStart: 'Follows m08-l01. First Light bars 7–8 moved to F major and to D major, 60 BPM. F major has Bb; D major has F# and C#.',
      skills: ['transposition'],
      glossary: ['transposition', 'major-scale'],
      blocks: [
        prose(
          undefined,
          'Two new keys, chosen because they introduce a flat and a pair of sharps. The degrees you are moving are 2–5–7–5 and then 3–2–1.',
        ),
        example('ex-m08-l02-a', 'First Light bars 7–8 in C major. Identify the degrees before moving them.'),
        prose(
          'Understand',
          'F major is F G A Bb C D E. Its key signature has one flat, and the flat is spelled Bb — never A#. D major is D E F# G A B C#, with two sharps.',
          'Spelling matters even though the sounds would be the same either way. It tells you which degree you are on, and that is what keeps the transfer musical rather than arithmetic.',
          'When you move the melody, the accompaniment has to move with it. A transposed melody over untransposed chords is a very common early mistake — and an audible one. If the chords under bars 7–8 were G and C in the original, they become C and F in F major, and A and D in D major.',
          'If both keys at once is too much, choose one and leave the other as a review variation. There is no benefit to rushing this.',
        ),
        exercise('q-m08-l02'),
        pianoTask(
          [
            'Name the degrees of bars 7–8 in C.',
            'Establish F major, then play those degrees with the transposed chords.',
            'Establish D major and repeat, watching for F# and C#.',
            'Play the final resolution in your chosen new key without returning to C first.',
          ],
          'If both keys overwhelm you, choose one and leave the other as a review variation.',
          'Transpose all eight bars of First Light to F major.',
        ),
        reflection('Did you move the chords along with the melody the first time, or only the melody?'),
      ],
      makeItYours: 'Choose the key you found easier and play one complete four-bar phrase in it, melody and bass roots together.',
      ifDifficult: [
        'If both keys at once overwhelm, choose one and leave the other as a review variation.',
        'Write the key signature out before you play.',
        'Remember a transposed accompaniment must move with the melody.',
      ],
      readinessCheck: 'Can you play the final resolution in either new key without returning to C?',
      takeaway: 'Move the chords with the melody, and spell the new key correctly.',
      reviewTask: 'Play one two-bar resolution in F or D major.',
      reviewExerciseId: 'q-m08-l02',
    },
    {
      id: 'm08-l03',
      title: 'Change the starting register',
      objective: 'Move a phrase by an octave while preserving its rhythm and contour, and distinguish that from changing key.',
      beforeYouStart: 'Follows m08-l02. C major, 60 BPM. Use the keyboard’s octave controls rather than squeezing all 88 keys onto the screen.',
      skills: ['transposition', 'pitch-mapping'],
      glossary: ['transposition', 'contour'],
      blocks: [
        prose(
          undefined,
          'Octave displacement and key change are different operations, and confusing them causes a lot of avoidable frustration.',
        ),
        example('ex-m08-l03-a', 'The same phrase played in two octaves. Nothing about the key has changed.'),
        prose(
          'Understand',
          'Moving a phrase an octave changes its register. Every degree stays the same, every interval stays the same, and the key signature is untouched. Moving a phrase to a new key changes which letters you play while keeping the degrees.',
          'Use the octave move for a practical purpose: transpose the phrase into a range where you can comfortably sing it. Singing your own phrases is the fastest feedback loop in this course, and a phrase two octaves above your voice cannot give you that.',
          'If a leap in the phrase runs off the visible keyboard, use the octave controls to move the whole view. Do not shrink the entire instrument onto the screen; small keys are harder to aim at and teach you nothing.',
          'Finally, a transfer task. Play or sing the phrase on another instrument if you have one. The musical content transfers immediately; the physical fingering has to be learned separately on every instrument.',
        ),
        exercise('q-m08-l03'),
        pianoTask(
          [
            'Play the phrase in its original octave.',
            'Play it one octave higher, preserving rhythm and contour exactly.',
            'Move it to a register where you can sing along, and sing it.',
            'Then play the same phrase in a different key and notice how different that operation felt.',
          ],
          'If a leap crosses the visible keyboard, use the octave controls rather than shrinking the keys.',
          'Try the phrase on another instrument, or sing it unaccompanied.',
        ),
        reflection('Which felt more like "the same music": the octave change, or the key change?'),
      ],
      makeItYours: 'Find the register where your own voice is most comfortable and mark it in Settings. Use it for every singing task from now on.',
      ifDifficult: [
        'If a leap crosses the visible keyboard, use octave controls instead of shrinking all 88 keys.',
        'Play the two octave versions back to back so the sameness is obvious.',
        'Keep the rhythm identical; only the register may change.',
      ],
      readinessCheck: 'Can you preserve rhythm and contour after moving an octave, then preserve degrees in one different key?',
      takeaway: 'Octave displacement changes register; transposition changes key.',
      reviewTask: 'Play one phrase in two octaves without changing its rhythm.',
      reviewExerciseId: 'q-m08-l03',
    },
    {
      id: 'm08-l04',
      title: 'A melody in three keys',
      objective: 'Play a four-bar phrase with root accompaniment in two keys with help, and attempt a third deliberately.',
      beforeYouStart: 'Follows m08-l03. First Light bars 5–8 or a four-bar phrase of your own. Keys C, G and F; D is optional.',
      skills: ['transposition', 'harmonization'],
      glossary: ['transposition', 'scale-degree'],
      blocks: [
        prose(
          undefined,
          'The final test of this module is whether a phrase belongs to you or to one key. Play the same four bars in three places.',
        ),
        example('ex-m08-l04-a', 'First Light bars 5–8 in C major, with its reference harmony.'),
        prose(
          'Understand',
          'Recall the degrees before you check any reference. The phrase is 6–6–5, then 3–2–1, then 2–5–7–5, then 3–2–1. Say them, then play them.',
          'Add root accompaniment in each key. In C that is F–C–G–C; in G it is C–G–D–G; in F it is Bb–F–C–F. Notice the chord degrees are identical in all three: IV–I–V–I.',
          'Record your readiness for each key separately. Averaging three keys into a single "ear skill" number would hide the useful information — which is usually that one particular degree, not the key as a whole, is causing the trouble.',
          'If errors do cluster around one degree, isolate that degree\'s resolution, practise it alone, and then rejoin the phrase.',
        ),
        exercise('q-m08-l04'),
        pianoTask(
          [
            'Say the four bars as degrees without playing.',
            'Play them in C with root accompaniment.',
            'Play them in G, then in F.',
            'Attempt D major deliberately, even if it needs help.',
          ],
          'If errors cluster around one scale degree, isolate that degree’s resolution and rejoin the phrase.',
          'Play the phrase in all four keys in succession without stopping.',
        ),
        reflection('Which key was hardest, and was it the key itself or one specific degree inside it?'),
      ],
      makeItYours: 'Take a four-bar phrase of your own instead of the study, and move it through the same three keys.',
      ifDifficult: [
        'If errors cluster around one degree, isolate that degree and rejoin the phrase.',
        'Record readiness per key rather than averaging everything into one score.',
        'Two keys with help is a complete result for this lesson.',
      ],
      readinessCheck: 'Can you complete the phrase in two keys with help, and make one additional key a deliberate attempt?',
      takeaway: 'A phrase you can play in three keys is a phrase you actually know.',
      reviewTask: 'Play one four-bar phrase in a key other than the one you learned it in.',
      reviewExerciseId: 'q-m08-l04',
    },
  ],
);
