import { example, exercise, makeModule, pianoTask, prose, reflection } from './builder';

export const module10 = makeModule(
  'm10',
  10,
  'Accompaniment styles for the music you like',
  'Choose a texture that suits a piece, and reduce music you love to something you can actually play.',
  [
    {
      id: 'm10-l01',
      title: 'A simple classical texture',
      objective: 'Keep a three-beat waltz grouping for four bars with a clear melody, and audition an Alberti figure in 4/4.',
      beforeYouStart: 'Follows Module 9. Little Waltz (S04) in 3/4 at 72 BPM, then First Light in 4/4. The count-in for 3/4 is one complete three-beat bar.',
      skills: ['accompaniment', 'arranging', 'coordination'],
      glossary: ['texture', 'arpeggio'],
      blocks: [
        prose(
          undefined,
          'Two textures here have long histories in keyboard music. Neither of them defines classical music, and using one does not make a piece classical — they are practical ways of spreading a chord under a melody.',
        ),
        example('ex-m10-l01-a', 'Little Waltz bars 1–4 in 3/4. Bass on beat 1, chords on beats 2 and 3.'),
        prose(
          'Understand',
          'The waltz pattern is only available in 3/4, and that restriction is deliberate. A 4/4 pattern cannot be squeezed into a three-beat bar by quietly dropping an event; every pattern in this app declares which meters it fits.',
          'Count one complete three-beat bar as your count-in. The default four-beat count-in belongs to the 4/4 studies and would put you on the wrong beat here.',
          'The Alberti figure is a 4/4 pattern: low, high, middle, high, in eighth notes, twice per bar. Audition it on First Light. It fills the bar much more densely than the waltz does, so if it starts to dominate, play fewer upper chord tones and soften them.',
        ),
        example('ex-m10-l01-b', 'First Light bars 1–4, a candidate for the Alberti figure. Listen to how much space the melody needs.'),
        exercise('q-m10-l01'),
        pianoTask(
          [
            'Count one three-beat bar, then play the waltz pattern on C for four bars.',
            'Add Little Waltz’s melody and keep the grouping steady.',
            'Switch to First Light and try the Alberti figure at a slow tempo.',
            'Soften the upper notes until the melody is clearly on top.',
          ],
          'If the pattern dominates, play fewer upper chord tones and soften them.',
          'Play all eight bars of Little Waltz with a consistent waltz accompaniment.',
        ),
        reflection('Which texture left more room for the melody, and why do you think that was?'),
      ],
      makeItYours: 'Take a four-bar progression of your own and play it once as a waltz in 3/4 and once with an Alberti figure in 4/4. Notice the melody has to change to fit.',
      ifDifficult: [
        'If the pattern dominates, play fewer upper chord tones and soften them.',
        'Use the three-beat count-in for 3/4, never the four-beat one.',
        'Slow the Alberti figure until each note is even.',
      ],
      readinessCheck: 'Can you keep Little Waltz’s three-beat grouping for four bars with a clear melody?',
      takeaway: 'A pattern belongs to a meter; it cannot be trimmed to fit another.',
      reviewTask: 'Play four bars of waltz accompaniment with a steady grouping.',
      reviewExerciseId: 'q-m10-l01',
    },
    {
      id: 'm10-l02',
      title: 'A pop ballad texture',
      objective: 'Choose one texture and play four bars without adding unplanned pauses at chord changes.',
      beforeYouStart: 'Follows m10-l01. Small Steps (S02), C major, 4/4, 68 BPM. All textures are compared at the same tempo.',
      skills: ['accompaniment', 'arranging'],
      glossary: ['texture', 'syncopation'],
      blocks: [
        prose(
          undefined,
          'Three textures, one melody, one tempo. Comparing them fairly means changing only the accompaniment.',
        ),
        example('ex-m10-l02-a', 'Small Steps bars 1–4. Try block chords, then bass-and-chord, then open broken.'),
        prose(
          'Understand',
          'Block chords are the most stable and the easiest to keep in time. Bass-and-chord adds movement without adding notes per beat. Open broken chords flow, but they spread the hand wider and are harder to keep quiet.',
          'Add the syncopated pop pattern only once one of the simpler versions is stable. Syncopation places chord attacks on the offbeats, which sounds good when the underlying beat is secure and confusing when it is not.',
          'If the syncopation obscures the beat for you, return to block chords and clap only the offbeat attacks until they feel located rather than random.',
          'One point about the music rather than the technique: a four-chord loop is a texture choice, not a complete account of how pop songs work. Plenty use more chords, mid-bar changes like the one in bar 7 of this study, or no loop at all.',
        ),
        exercise('q-m10-l02'),
        pianoTask(
          [
            'Play bars 1–4 with block chords at 68 BPM.',
            'Repeat with bass-and-chord, then with open broken chords.',
            'Choose one and play four bars with no pause at any change.',
            'Only then, try the syncopated pattern.',
          ],
          'If syncopation obscures the beat, return to block chords and clap the offbeat attacks.',
          'Play bars 5–8, including the mid-bar F-to-G change in bar 7.',
        ),
        reflection('Which texture did you choose, and was it the one that sounded best or the one that stayed steadiest?'),
      ],
      makeItYours: 'Play the same four bars with the texture you think suits the melody least, and say in one sentence why it does not fit.',
      ifDifficult: [
        'If syncopation obscures the beat, return to block chords and clap the offbeat attacks.',
        'Keep the tempo identical across all comparisons.',
        'Split the mid-bar chord change in bar 7 rather than holding F across it.',
      ],
      readinessCheck: 'Can you choose one texture and play four bars without adding unplanned pauses at changes?',
      takeaway: 'Choose the texture you can keep steady, then make it more interesting.',
      reviewTask: 'Play four bars of one pop texture at a steady tempo.',
      reviewExerciseId: 'q-m10-l02',
    },
    {
      id: 'm10-l03',
      title: 'A lyrical texture with added colour',
      objective: 'Play one four-bar phrase with a singing melody and decide whether an added ninth helps.',
      beforeYouStart: 'Follows m10-l02. Skyward Letter (S05), C major, 4/4, 64 BPM. Its progression is IV–V–iii–vi then ii–V–I–I.',
      skills: ['arranging', 'accompaniment', 'chord-hearing'],
      glossary: ['add9', 'texture'],
      blocks: [
        prose(
          undefined,
          'Skyward Letter is an original study written for this course. It is not a transcription of any soundtrack, and its progression is not a formula that defines any genre.',
        ),
        example('ex-m10-l03-a', 'Bars 1–4: F–G–Em–Am, that is IV–V–iii–vi. Hear it with roots first.'),
        prose(
          'Understand',
          'Two labels need explaining. iii in C major is E minor, E–G–B — a chord you have played but not named by numeral before. And add9 means an added ninth: Cadd9 is C–E–G–D, a plain C triad with a D above it. No seventh is implied, and it is not the same as Csus2, which would replace the E with D rather than adding to it.',
          'Hear the melody first with bass roots only, so the long notes and phrase shape are audible. Then add flowing broken chords, keeping them quieter than the melody as you practised in Module 5.',
          'Finally, audition Cadd9 at the final tonic. Some people find the added D opens the ending out; others find it distracting. Decide for this piece rather than in general, and if it distracts you, use plain triads.',
        ),
        example('ex-m10-l03-b', 'Bars 5–8: Dm–G–C–C, that is ii–V–I–I. The optional variant uses Cadd9 at the end.'),
        exercise('q-m10-l03'),
        pianoTask(
          [
            'Play bars 1–4 with bass roots and a singing melody.',
            'Add a flowing broken-chord pattern, kept quiet.',
            'Play the final bars with a plain C triad, then with Cadd9.',
            'Choose one and say why.',
          ],
          'If the added colour is distracting, use plain triads throughout.',
          'Play all eight bars with one consistent texture and your chosen ending.',
        ),
        reflection('Did the added ninth change the ending for you, or was the difference too small to matter here?'),
      ],
      makeItYours: 'Use Cadd9 at the end of one of your own phrases and decide whether you want it there.',
      ifDifficult: [
        'If the colour is distracting, use plain triads.',
        'Play bass roots under the whole melody before adding any pattern.',
        'Remember add9 adds a note; sus2 replaces the third.',
      ],
      readinessCheck: 'Can you play one four-bar phrase with a singing melody and choose whether the added note helps?',
      takeaway: 'Added colour is a local decision about one chord in one piece.',
      reviewTask: 'Play one phrase with plain triads and then with an added ninth.',
      reviewExerciseId: 'q-m10-l03',
    },
    {
      id: 'm10-l04',
      title: 'Simplify music you love',
      objective: 'Create a playable four-to-eight-bar reduction of a piece and identify what you removed.',
      beforeYouStart: 'Follows m10-l03. Use Skyward Letter or a piece of your own choosing. The app provides a worksheet; it does not transcribe recordings or analyse audio.',
      skills: ['arranging', 'harmonization'],
      glossary: ['lead-sheet', 'texture', 'harmonic-rhythm'],
      blocks: [
        prose(
          undefined,
          'Most music you want to play is more difficult than the version you need in order to start playing it. Reduction is the skill that closes that gap, and it is a musical decision rather than a technical shortcut.',
        ),
        example('ex-m10-l04-a', 'Skyward Letter bars 1–4 reduced to melody and bass roots. Everything else has been removed.'),
        prose(
          'Understand',
          'Reduce in a fixed order. Keep the melody. Keep the bass roots. Write down the chord symbols. Mark the phrase lengths. Then remove ornamental runs and inner voices first, because they carry the least structural weight.',
          'Play the skeleton before you add anything back. If the skeleton does not sound like the piece, your chord symbols are probably wrong — go back and check them against the melody rather than adding notes to cover the problem.',
          'Then add one accompaniment pattern. One is usually enough; the reduction is meant to be playable now, not eventually.',
          'If your chosen piece is too difficult to hear accurately, use the included study and transfer the process to your own music later. Being unable to hear a dense arrangement is normal and is not a failure of this lesson.',
        ),
        exercise('q-m10-l04'),
        pianoTask(
          [
            'Choose a piece, or use Skyward Letter.',
            'Write melody, bass roots, chord symbols and phrase lengths on the worksheet.',
            'Play the skeleton with no pattern at all.',
            'Add one accompaniment pattern and play four to eight bars.',
          ],
          'If your source material is too difficult to hear, use the included study and transfer the process later.',
          'Reduce a second contrasting piece and compare how much you had to remove.',
        ),
        reflection('What did you remove, and did the piece still sound like itself without it?'),
      ],
      makeItYours: 'Save your reduction in the notebook with a list of what you left out. Revisit it after Module 12 and add one thing back.',
      ifDifficult: [
        'If the source is too difficult to hear, use the included study.',
        'Play the skeleton alone before adding any pattern.',
        'Remove ornamental runs and inner voices before anything structural.',
      ],
      readinessCheck: 'Can you create a playable four-to-eight-bar reduction and identify what was removed?',
      takeaway: 'A reduction you can play today is worth more than an arrangement you cannot.',
      reviewTask: 'Reduce two bars of any piece to melody and bass roots.',
      reviewExerciseId: 'q-m10-l04',
    },
  ],
);
