import { example, exercise, makeModule, pianoTask, prose, reflection } from './builder';

export const module11 = makeModule(
  'm11',
  11,
  'A familiar ground as a bridge to independent playing',
  'Use a well-known harmonic sequence as a workshop: write a melody on it, vary its texture, and move it to another key.',
  [
    {
      id: 'm11-l01',
      title: 'Understand the familiar harmonic ground',
      objective: 'Play the eight-chord root sequence in D major from a degree prompt and recognise its return to the start.',
      beforeYouStart: 'Follows Module 10. D major, 4/4, 60 BPM, one bar per chord. D major contains F# and C#. No score from your own arrangement of Canon in D is needed.',
      skills: ['harmonization', 'transposition'],
      glossary: ['roman-numeral', 'transposition'],
      blocks: [
        prose(
          undefined,
          'You can already play an arrangement of Canon in D. This module uses its harmonic ground as teaching material — not as a transcription of your arrangement, and not with any claim about its timing.',
        ),
        example('ex-m11-l01-a', 'D–A–Bm–F#m–G–D–G–A, one bar per chord. That is a simplification for teaching, not a reproduction of any particular arrangement.'),
        prose(
          'Understand',
          'As Roman numerals the sequence is I–V–vi–iii–IV–I–IV–V. Reading it that way is what will let you move it to another key in lesson 4 of this module.',
          'Play and sing the bass roots: D, A, B, F#, G, D, G, A. Notice they descend for the first four chords and then step around. Singing the bass is the fastest way to memorise a progression.',
          'Identify F# and C# as the key\'s sharps. Both appear in the chords: F# is the root of F#m and the third of D; C# is the third of A.',
          'The loop ends on A, which is V. It has not closed on the tonic, and the usual reason to play it is that it returns to the beginning. If you want a standalone ending, Module 11 lesson 3 offers one.',
        ),
        example('ex-m11-l01-b', 'The bass roots alone. Sing along with them twice.'),
        exercise('q-m11-l01'),
        pianoTask(
          [
            'Play the eight bass roots slowly, one per bar.',
            'Sing them while you play.',
            'Split the sequence into two groups of four and play each from memory.',
            'Play the whole root sequence from the degree prompt I–V–vi–iii–IV–I–IV–V.',
          ],
          'If eight chords is too long, split it into two groups of four and learn them separately.',
          'Add compact triads above the roots for the whole sequence.',
        ),
        reflection('Which of the eight chords was hardest to recall, and where does it sit in the sequence?'),
      ],
      makeItYours: 'Play the root sequence four times in a row as a continuous loop, and notice the moment where it turns back to the beginning.',
      ifDifficult: [
        'If the sequence is long, split it into two four-chord groups.',
        'Sing the bass roots rather than reading the symbols.',
        'No score from your own arrangement is required for any part of this module.',
      ],
      readinessCheck: 'Can you play the root sequence from a degree prompt and recognise its return to the start?',
      takeaway: 'A ground is a repeating harmonic shape you can build many different melodies on.',
      reviewTask: 'Play the eight-chord root sequence from its Roman numerals.',
      reviewExerciseId: 'q-m11-l01',
    },
    {
      id: 'm11-l02',
      title: 'Write your own melody on the ground',
      objective: 'Repeat an original four-bar phrase of your own over the first half of the progression.',
      beforeYouStart: 'Follows m11-l01. D major, 4/4, 60 BPM. Ground and Wings (S06) is a demonstration written for this course, not a transcription of Canon’s melody.',
      skills: ['improvisation', 'harmonization'],
      glossary: ['target-tone', 'motif'],
      blocks: [
        prose(
          undefined,
          'A ground is useful precisely because the harmony is fixed. With the chords decided, all your attention can go to the melody.',
        ),
        example('ex-m11-l02-a', 'Ground and Wings bars 1–4 — a new melody written over the first half of the ground, as a demonstration of what you are about to do.'),
        prose(
          'Understand',
          'Use the method from Module 6. Choose one target chord tone per bar first: over D you might choose F#, over A choose E, over Bm choose D, over F#m choose C#. Four notes, one per bar, is a complete plan.',
          'Then sing a melody that reaches those targets before you play anything. Singing first is what stops the phrase from becoming a memorised finger pattern.',
          'Work in two-bar chunks and leave rests. A melody over a slow-moving ground does not need to fill every beat; the harmony is already carrying the music forward.',
          'If what you play starts sounding like finger habits rather than an idea, walk away from the keys, sing a rhythm, then come back and reproduce it.',
        ),
        exercise('q-m11-l02'),
        pianoTask(
          [
            'Choose one target chord tone for each of the first four bars.',
            'Play only those four notes over the progression.',
            'Sing a melody that connects them, then find it.',
            'Repeat your four-bar phrase twice so it becomes fixed.',
          ],
          'If it sounds like memorised finger patterns, sing a rhythm away from the keyboard and return to reproduce it.',
          'Write a second four-bar phrase over bars 5–8 of the ground.',
        ),
        reflection('Did your melody come from the targets, or did the targets come from what your hands wanted to play?'),
      ],
      makeItYours: 'Save your four-bar melody in the notebook, linked to this lesson. You will arrange it in the next lesson.',
      ifDifficult: [
        'If it sounds like finger patterns, sing away from the keys and return.',
        'Work in two-bar chunks and leave rests.',
        'One target note per bar is a complete plan; you do not need more.',
      ],
      readinessCheck: 'Can you repeat an original four-bar phrase over the first half of the progression?',
      takeaway: 'Fixed harmony frees your attention for melody.',
      reviewTask: 'Improvise two bars over the ground, landing on a chosen target.',
      reviewExerciseId: 'q-m11-l02',
    },
    {
      id: 'm11-l03',
      title: 'Vary density and register',
      objective: 'Perform two contrasting four-bar arrangements of the same melody and describe how their textures differ.',
      beforeYouStart: 'Follows m11-l02. D major, 4/4, 60 BPM. Use Ground and Wings or your own melody from the previous lesson.',
      skills: ['arranging', 'accompaniment'],
      glossary: ['texture', 'voicing', 'arpeggio'],
      blocks: [
        prose(
          undefined,
          'The same melody and the same harmony can be presented in very different ways. Density and register are the two easiest dials to turn.',
        ),
        example('ex-m11-l03-a', 'Ground and Wings bars 5–8. Arrange these once with block chords and once with broken chords.'),
        prose(
          'Understand',
          'Make three versions. First, block chords: dense, stable, easy to keep in time. Second, broken chords: the same harmony spread across the beat, lighter and more flowing. Third, the melody an octave higher, where it is comfortable.',
          'Keep the harmonic sequence recognisable in all three. If a listener cannot tell that these are versions of the same thing, you changed the harmony rather than the texture.',
          'Register has a cost. Moving the melody up can make it brighter, or it can thin it out and weaken it. If the higher octave weakens your melody, choose a nearer register instead — the point is to make a choice by listening, not to move as far as possible.',
          'Save these as arrangements that reference the same melody, not as separate unrelated pieces. That is how the notebook stores them.',
        ),
        exercise('q-m11-l03'),
        pianoTask(
          [
            'Play four bars with block chords.',
            'Play the same four bars with broken chords.',
            'Play them once more with the melody an octave higher.',
            'Choose two contrasting versions and perform them back to back.',
          ],
          'If octave placement weakens the melody, choose a nearer register instead.',
          'Repeat the second four-bar phrase with a changed ending as an additional variation.',
        ),
        reflection('Describe the difference between your two versions in one sentence, without using the word "better".'),
      ],
      makeItYours: 'Save both versions as arrangements of the same notebook melody, each with a one-line comment.',
      ifDifficult: [
        'If octave placement weakens the melody, choose a nearer register.',
        'Keep the harmony identical across versions; change only texture and register.',
        'Save arrangements against one melody rather than duplicating the melody.',
      ],
      readinessCheck: 'Can you perform two contrasting four-bar versions and describe how their textures differ?',
      takeaway: 'Texture and register are choices you make after the notes are decided.',
      reviewTask: 'Play one phrase with two different accompaniment densities.',
      reviewExerciseId: 'q-m11-l03',
    },
    {
      id: 'm11-l04',
      title: 'Move the ground to C',
      objective: 'Play the root sequence in C major and transfer two bars of melody into it using degrees.',
      beforeYouStart: 'Follows m11-l03. C major, 4/4, 60 BPM. The sequence becomes C–G–Am–Em–F–C–F–G.',
      skills: ['transposition', 'improvisation'],
      glossary: ['transposition', 'roman-numeral'],
      blocks: [
        prose(
          undefined,
          'The clearest proof that you understand a progression is being able to play it somewhere else. Here the ground moves from D major to C major.',
        ),
        example('ex-m11-l04-a', 'The ground in C: C–G–Am–Em–F–C–F–G. The numerals are unchanged.'),
        prose(
          'Understand',
          'Do not calculate semitones. Write the sequence as I–V–vi–iii–IV–I–IV–V and build each chord from C. That is faster, less error-prone, and it is the same process you would use for any other key.',
          'Then transfer two bars of Ground and Wings — or of your own melody — using degrees rather than note names. The demonstration below shows the first two bars in C.',
          'Finally, improvise a new short phrase in C without reading the D-major notes at all. The point of the module is that the musical content moved, not just the letters.',
          'When you finish, compare two things honestly: what musical knowledge transferred immediately, and which hand movements needed fresh practice. They are rarely the same list.',
        ),
        example('ex-m11-l04-b', 'Two bars of Ground and Wings moved to C major, by degrees.'),
        exercise('q-m11-l04'),
        pianoTask(
          [
            'Write the progression as Roman numerals and build it from C.',
            'Play the eight roots in C.',
            'Transfer two bars of melody using degrees.',
            'Improvise a new short phrase in C without looking at the D version.',
          ],
          'If semitone calculations slow everything down, write the roots as I–V–vi–iii–IV–I–IV–V and build them from C.',
          'Move the ground to G major as well and play its roots.',
        ),
        reflection('What transferred immediately, and what needed fresh practice with your hands?'),
      ],
      makeItYours: 'Play your own Ground and Wings melody in C major and save it as a transposed arrangement.',
      ifDifficult: [
        'If semitone calculations slow you down, build from Roman numerals instead.',
        'Play the roots alone in the new key before adding any melody.',
        'Two transferred bars is a complete result.',
      ],
      readinessCheck: 'Can you play the C root sequence and one transferred phrase?',
      takeaway: 'Numerals move a progression faster than arithmetic does.',
      reviewTask: 'Play the ground’s roots in C from its Roman numerals.',
      reviewExerciseId: 'q-m11-l04',
    },
  ],
);
